# generated by datamodel-codegen:
#   filename:  tmpvdlkjgsq.json
#   timestamp: 2025-05-13T07:46:36+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import Field
from sparkdantic import SparkModel

from .reference_model import ReferenceModel


class ApplicationUnits(str, Enum):
    AMOUNT = 'Amount'
    HOURS = 'Hours'
    INCIDENTS = 'Incidents'


class ApplicationCycle(str, Enum):
    CONTRACT2_WEEKS = 'Contract2Weeks'
    CONTRACT4_WEEKS = 'Contract4Weeks'
    CONTRACT_YEAR = 'ContractYear'
    CALENDAR_MONTH = 'CalendarMonth'
    CALENDAR_QUARTER = 'CalendarQuarter'
    CALENDAR_WEEK = 'CalendarWeek'
    CONTRACT_QUARTER = 'ContractQuarter'
    CALENDAR_YEAR = 'CalendarYear'


class EmployeeCompRate(str, Enum):
    """
    Required On Updates;
    """
    ACTUAL = 'Actual'
    HOURLY = 'Hourly'


class EmployeeCompNotExceed(str, Enum):
    BILLING = 'Billing'
    AMOUNT = 'Amount'
    PERCENT = 'Percent'


class InvoicingCycle(str, Enum):
    """
    Required On Updates;
    """
    CONTRACT_YEAR = 'ContractYear'
    CALENDAR_YEAR = 'CalendarYear'


class BillTime(str, Enum):
    """
    Required On Updates;
    """
    BILLABLE = 'Billable'
    DO_NOT_BILL = 'DoNotBill'
    NO_CHARGE = 'NoCharge'
    NO_DEFAULT = 'NoDefault'


class BillExpenses(str, Enum):
    """
    Required On Updates;
    """
    BILLABLE = 'Billable'
    DO_NOT_BILL = 'DoNotBill'
    NO_CHARGE = 'NoCharge'
    NO_DEFAULT = 'NoDefault'


class BillProducts(str, Enum):
    """
    Required On Updates;
    """
    BILLABLE = 'Billable'
    DO_NOT_BILL = 'DoNotBill'
    NO_CHARGE = 'NoCharge'
    NO_DEFAULT = 'NoDefault'


class PeriodType(str, Enum):
    CURRENT = 'Current'
    FUTURE = 'Future'
    BOTH = 'Both'
    UNDEFINED = 'Undefined'


class AgreementStatus(str, Enum):
    ACTIVE = 'Active'
    CANCELLED = 'Cancelled'
    EXPIRED = 'Expired'
    INACTIVE = 'Inactive'


# Reference types as proper models instead of RootModel
class AgreementReference(ReferenceModel):
    """Reference to an Agreement"""
    pass


class AgreementTypeReference(ReferenceModel):
    """Reference to an AgreementType"""
    pass


class BillingCycleReference(ReferenceModel):
    """Reference to a BillingCycle"""
    pass


class BillingTermsReference(ReferenceModel):
    """Reference to BillingTerms"""
    pass


class CompanyReference(ReferenceModel):
    """Reference to a Company"""
    pass


class ContactReference(ReferenceModel):
    """Reference to a Contact"""
    pass


class CurrencyReference(ReferenceModel):
    """Reference to a Currency"""
    pass


class InvoiceTemplateReference(ReferenceModel):
    """Reference to an InvoiceTemplate"""
    pass


class OpportunityReference(ReferenceModel):
    """Reference to an Opportunity"""
    pass


class ProjectTypeReference(ReferenceModel):
    """Reference to a ProjectType"""
    pass


class SLAReference(ReferenceModel):
    """Reference to an SLA"""
    pass


class SiteReference(ReferenceModel):
    """Reference to a Site"""
    pass


class SystemDepartmentReference(ReferenceModel):
    """Reference to a SystemDepartment"""
    pass


class SystemLocationReference(ReferenceModel):
    """Reference to a SystemLocation"""
    pass


class TaxCodeReference(ReferenceModel):
    """Reference to a TaxCode"""
    pass


class WorkRoleReference(ReferenceModel):
    """Reference to a WorkRole"""
    pass


class WorkTypeReference(ReferenceModel):
    """Reference to a WorkType"""
    pass


class Agreement(SparkModel):
    class Config:
        validate_by_name = True

    id: int | None = None
    name: str = Field(..., description=' Max length: 100;')
    type: AgreementTypeReference
    company: CompanyReference
    contact: ContactReference
    site: SiteReference | None = None
    subContractCompany: CompanyReference | None = None
    subContractContact: ContactReference | None = None
    parentAgreement: AgreementReference | None = None
    customerPO: str | None = Field(None, description=' Max length: 50;')
    location: SystemLocationReference | None = None
    department: SystemDepartmentReference | None = None
    restrictLocationFlag: bool | None = None
    restrictDepartmentFlag: bool | None = None
    startDate: datetime | None = None
    endDate: datetime | None = None
    noEndingDateFlag: bool | None = None
    opportunity: OpportunityReference | None = None
    cancelledFlag: bool | None = None
    dateCancelled: datetime | None = None
    reasonCancelled: str | None = Field(None, description=' Max length: 100;')
    sla: SLAReference | None = None
    workOrder: str | None = Field(None, description=' Max length: 20;')
    internalNotes: str | None = None
    applicationUnits: ApplicationUnits | None = None
    applicationLimit: float | None = None
    applicationCycle: ApplicationCycle | None = None
    applicationUnlimitedFlag: bool | None = None
    oneTimeFlag: bool | None = None
    coverAgreementTime: bool | None = None
    coverAgreementProduct: bool | None = None
    coverAgreementExpense: bool | None = None
    coverSalesTax: bool | None = None
    carryOverUnused: bool | None = None
    allowOverruns: bool | None = None
    expiredDays: int | None = None
    limit: int | None = None
    expireWhenZero: bool | None = None
    chargeToFirm: bool | None = None
    employeeCompRate: EmployeeCompRate | None = Field(
        None, description=' Required On Updates;'
    )
    employeeCompNotExceed: EmployeeCompNotExceed | None = None
    compHourlyRate: float | None = None
    compLimitAmount: float | None = None
    billingCycle: BillingCycleReference | None = None
    billOneTimeFlag: bool | None = None
    billingTerms: BillingTermsReference | None = None
    invoicingCycle: InvoicingCycle | None = Field(
        None, description=' Required On Updates;'
    )
    billToCompany: CompanyReference | None = None
    billToContact: ContactReference | None = None
    billToSite: SiteReference | None = None
    billAmount: float | None = None
    taxable: bool | None = None
    prorateFirstBill: float | None = None
    billStartDate: datetime | None = None
    taxCode: TaxCodeReference | None = None
    restrictDownPayment: bool | None = None
    prorateFlag: bool | None = None
    invoiceProratedAdditionsFlag: bool | None = None
    invoiceDescription: str | None = None
    topComment: bool | None = None
    bottomComment: bool | None = None
    workRole: WorkRoleReference | None = None
    workType: WorkTypeReference | None = None
    projectType: ProjectTypeReference | None = None
    invoiceTemplate: InvoiceTemplateReference | None = None
    billTime: BillTime | None = Field(None, description=' Required On Updates;')
    billExpenses: BillExpenses | None = Field(None, description=' Required On Updates;')
    billProducts: BillProducts | None = Field(None, description=' Required On Updates;')
    billableTimeInvoice: bool | None = None
    billableExpenseInvoice: bool | None = None
    billableProductInvoice: bool | None = None
    currency: CurrencyReference | None = None
    periodType: PeriodType | None = None
    autoInvoiceFlag: bool | None = None
    nextInvoiceDate: str | None = None
    companyLocation: SystemLocationReference | None = None
    shipToCompany: CompanyReference | None = None
    shipToContact: ContactReference | None = None
    shipToSite: SiteReference | None = None
    agreementStatus: AgreementStatus | None = None