# generated by datamodel-codegen:
#   filename:  tmpt_kyduoo.json
#   timestamp: 2025-05-13T07:46:39+00:00

from __future__ import annotations

import warnings
# Filter Pydantic deprecation warnings for Config options
warnings.filterwarnings("ignore", message="Valid config keys have changed in V2")

from typing import Any, Optional

from pydantic import Field
from sparkdantic import SparkModel

from fabric_api.connectwise_models.reference_model import (
    CompanyReference, MemberReference, ClassificationReference, 
    CurrencyReference, ExpenseReportReference, PaymentMethodReference,
    TypeReference
)


class ExpenseEntry(SparkModel):
    class Config:
        allow_population_by_field_name = True

    id: int = Field(..., description='')
    expenseReport: ExpenseReportReference = Field(..., description='')
    company: CompanyReference = Field(..., description='')
    chargeToId: int = Field(..., description='')
    chargeToType: str = Field(..., description='')
    type: TypeReference = Field(..., description='')
    member: MemberReference = Field(..., description='')
    paymentMethod: PaymentMethodReference = Field(..., description='')
    classification: ClassificationReference = Field(..., description='')
    amount: float = Field(..., description='')
    billableOption: str = Field(..., description='')
    date: str = Field(..., description='')
    locationId: int = Field(..., description='')
    businessUnitId: int = Field(..., description='')
    invoiceAmount: float = Field(..., description='')
    mobileGuid: str = Field(..., description='')
    currency: CurrencyReference = Field(..., description='')
    status: str = Field(..., description='')
    billAmount: float = Field(..., description='')
    agreementAmount: float = Field(..., description='')
