# generated by datamodel-codegen:
#   filename:  tmppruq3bzu.json
#   timestamp: 2025-05-13T07:40:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import Field
from sparkdantic import SparkModel

from .reference_model import ReferenceModel


class Type(str, Enum):
    AGREEMENT = 'Agreement'
    CREDIT_MEMO = 'CreditMemo'
    DOWN_PAYMENT = 'DownPayment'
    MISCELLANEOUS = 'Miscellaneous'
    PROGRESS = 'Progress'
    STANDARD = 'Standard'


class ApplyToType(str, Enum):
    ALL = 'All'
    AGREEMENT = 'Agreement'
    PROJECT = 'Project'
    PROJECT_PHASE = 'ProjectPhase'
    SALES_ORDER = 'SalesOrder'
    TICKET = 'Ticket'


# Reference types using concrete model
class AgreementReference(ReferenceModel):
    """Reference to an Agreement"""
    pass


class BatchReference(ReferenceModel):
    """Reference to a Batch"""
    pass


class BillingSetupReference(ReferenceModel):
    """Reference to a BillingSetup"""
    pass


class BillingStatusReference(ReferenceModel):
    """Reference to a BillingStatus"""
    pass


class BillingTermsReference(ReferenceModel):
    """Reference to BillingTerms"""
    pass


class BillingUnitReference(ReferenceModel):
    """Reference to a BillingUnit"""
    pass


class CompanyReference(ReferenceModel):
    """Reference to a Company"""
    pass


class CurrencyReference(ReferenceModel):
    """Reference to a Currency"""
    pass


class InvoiceTemplateDetailReference(ReferenceModel):
    """Reference to an InvoiceTemplateDetail"""
    pass


class ProjectPhaseReference(ReferenceModel):
    """Reference to a ProjectPhase"""
    pass


class ProjectReference(ReferenceModel):
    """Reference to a Project"""
    pass


class SalesOrderReference(ReferenceModel):
    """Reference to a SalesOrder"""
    pass


class SiteReference(ReferenceModel):
    """Reference to a Site"""
    pass


class SystemLocationReference(ReferenceModel):
    """Reference to a SystemLocation"""
    pass


class TaxCodeReference(ReferenceModel):
    """Reference to a TaxCode"""
    pass


class TicketReference(ReferenceModel):
    """Reference to a Ticket"""
    pass


class PostedInvoice(SparkModel):
    class Config:
        validate_by_name = True

    id: int | None = None
    invoiceNumber: str | None = Field(
        None, description=' Max length: 15; Required On Updates;'
    )
    type: Type | None = None
    status: BillingStatusReference | None = None
    company: CompanyReference
    billToCompany: CompanyReference | None = None
    shipToCompany: CompanyReference | None = None
    accountNumber: str | None = None
    applyToType: ApplyToType | None = None
    applyToId: int | None = None
    attention: str | None = Field(None, description=' Max length: 60;')
    shipToAttention: str | None = Field(None, description=' Max length: 60;')
    billingSite: SiteReference | None = None
    billingSiteAddressLine1: str | None = None
    billingSiteAddressLine2: str | None = None
    billingSiteCity: str | None = None
    billingSiteState: str | None = None
    billingSiteZip: str | None = None
    billingSiteCountry: str | None = None
    shippingSite: SiteReference | None = None
    shippingSiteAddressLine1: str | None = None
    shippingSiteAddressLine2: str | None = None
    shippingSiteCity: str | None = None
    shippingSiteState: str | None = None
    shippingSiteZip: str | None = None
    shippingSiteCountry: str | None = None
    billingTerms: BillingTermsReference | None = None
    reference: str | None = Field(None, description=' Max length: 50;')
    customerPO: str | None = Field(None, description=' Max length: 50;')
    templateSetupId: int | None = Field(
        None, description='Can be obtained via InvoiceTemplate report.'
    )
    invoiceTemplate: InvoiceTemplateDetailReference | None = None
    emailTemplateId: int | None = Field(
        None, description='Can be obtained via InvoiceEmailTemplate report.'
    )
    addToBatchEmailList: bool | None = None
    date: datetime | None = None
    restrictDownpaymentFlag: bool | None = None
    locationId: int | None = Field(None, description=' Required On Updates;')
    location: SystemLocationReference | None = None
    departmentId: int | None = Field(
        None, description='departmentId is only required for special invoices.'
    )
    department: BillingUnitReference | None = None
    territoryId: int | None = None
    territory: SystemLocationReference | None = None
    topComment: str | None = None
    bottomComment: str | None = None
    taxableFlag: bool | None = None
    taxCode: TaxCodeReference | None = None
    internalNotes: str | None = None
    downpaymentPreviouslyTaxedFlag: bool | None = None
    serviceTotal: float | None = None
    overrideDownPaymentAmountFlag: bool | None = None
    currency: CurrencyReference | None = None
    dueDate: datetime | None = None
    expenseTotal: float | None = None
    productTotal: float | None = None
    previousProgressApplied: float | None = None
    serviceAdjustmentAmount: float | None = None
    agreementAmount: float | None = None
    downpaymentApplied: float | None = None
    subtotal: float | None = None
    total: float | None = None
    remainingDownpayment: float | None = None
    salesTax: float | None = None
    adjustmentReason: str | None = None
    adjustedBy: str | None = None
    closedBy: str | None = None
    payments: float | None = None
    credits: float | None = None
    balance: float | None = None
    specialInvoiceFlag: bool | None = None
    billingSetupReference: BillingSetupReference | None = None
    ticket: TicketReference | None = None
    project: ProjectReference | None = None
    phase: ProjectPhaseReference | None = None
    salesOrder: SalesOrderReference | None = None
    agreement: AgreementReference | None = None
    glBatch: BatchReference | None = None
    unbatchedBatch: BatchReference | None = None