# generated by datamodel-codegen:
#   filename:  tmpp2npg7va.json
#   timestamp: 2025-05-13T07:46:41+00:00

from __future__ import annotations

import warnings
# Filter Pydantic deprecation warnings for Config options
warnings.filterwarnings("ignore", message="Valid config keys have changed in V2")

from typing import Any, Optional

from pydantic import Field
from sparkdantic import SparkModel

from fabric_api.connectwise_models.reference_model import (
    CompanyReference, CatalogItemReference, BusinessUnitReference,
    LocationReference, OpportunityReference, TaxCodeReference, 
    UnitOfMeasureReference
)


class ProductItem(SparkModel):
    class Config:
        allow_population_by_field_name = True

    id: int = Field(..., description='')
    catalogItem: CatalogItemReference = Field(..., description='')
    description: str = Field(..., description='')
    sequenceNumber: float = Field(..., description='')
    quantity: float = Field(..., description='')
    unitOfMeasure: UnitOfMeasureReference = Field(..., description='')
    price: float = Field(..., description='')
    cost: float = Field(..., description='')
    extPrice: float = Field(..., description='')
    extCost: float = Field(..., description='')
    margin: float = Field(..., description='')
    agreementAmount: float = Field(..., description='')
    priceMethod: str = Field(..., description='')
    billableOption: str = Field(..., description='')
    locationId: int = Field(..., description='')
    location: LocationReference = Field(..., description='')
    businessUnitId: int = Field(..., description='')
    businessUnit: BusinessUnitReference = Field(..., description='')
    vendorSku: str = Field(..., description='')
    taxableFlag: int = Field(..., description='')
    dropshipFlag: int = Field(..., description='')
    specialOrderFlag: int = Field(..., description='')
    phaseProductFlag: int = Field(..., description='')
    cancelledFlag: int = Field(..., description='')
    quantityCancelled: float = Field(..., description='')
    cancelledReason: str = Field(..., description='')
    customerDescription: str = Field(..., description='')
    productSuppliedFlag: int = Field(..., description='')
    subContractorAmountLimit: float = Field(..., description='')
    opportunity: OpportunityReference = Field(..., description='')
    calculatedPriceFlag: int = Field(..., description='')
    calculatedCostFlag: int = Field(..., description='')
    forecastDetailId: int = Field(..., description='')
    cancelledBy: int = Field(..., description='')
    cancelledDate: str = Field(..., description='')
    taxCode: TaxCodeReference = Field(..., description='')
    listPrice: float = Field(..., description='')
    company: CompanyReference = Field(..., description='')
    productClass: str = Field(..., description='')
    needToPurchaseFlag: int = Field(..., description='')
    minimumStockFlag: int = Field(..., description='')
    poApprovedFlag: int = Field(..., description='')
    uom: str = Field(..., description='')
