# generated by datamodel-codegen:
#   filename:  tmp6xt_q4wv.json
#   timestamp: 2025-05-13T07:46:37+00:00

from __future__ import annotations

import warnings
# Filter Pydantic deprecation warnings for Config options
warnings.filterwarnings("ignore", message="Valid config keys have changed in V2")

from typing import Any

from pydantic import Field
from sparkdantic import SparkModel

from fabric_api.connectwise_models.agreement import CompanyReference
from fabric_api.connectwise_models.reference_model import (
    MemberReference, LocationReference, DepartmentReference, 
    WorkTypeReference, WorkRoleReference, TimeSheetReference,
    ProjectReference, PhaseReference, TaxCodeReference
)


class FieldInfo(SparkModel):
    class Config:
        allow_population_by_field_name = True

    ticket_href: str | None = Field(None, description='')
    billingMethod: str | None = Field(None, description='')
    status: str | None = Field(None, description='')


class Ticket(SparkModel):
    class Config:
        allow_population_by_field_name = True

    id: int | None = Field(None, description='')
    summary: str | None = Field(None, description='')
    field_info: FieldInfo | None = Field(None, alias='_info', description='')


class TimeEntry(SparkModel):
    class Config:
        allow_population_by_field_name = True

    id: int = Field(..., description='')
    company: CompanyReference = Field(..., description='')
    companyType: str = Field(..., description='')
    chargeToId: int = Field(..., description='')
    chargeToType: str = Field(..., description='')
    member: MemberReference = Field(..., description='')
    locationId: int = Field(..., description='')
    businessUnitId: int = Field(..., description='')
    businessGroupDesc: str = Field(..., description='')
    location: LocationReference = Field(..., description='')
    department: DepartmentReference = Field(..., description='')
    workType: WorkTypeReference = Field(..., description='')
    workRole: WorkRoleReference = Field(..., description='')
    projectActivity: str = Field(..., description='')
    territory: str = Field(..., description='')
    timeStart: str = Field(..., description='')
    timeEnd: str = Field(..., description='')
    hoursDeduct: float = Field(..., description='')
    actualHours: float = Field(..., description='')
    billableOption: str = Field(..., description='')
    addToDetailDescriptionFlag: int = Field(..., description='')
    addToInternalAnalysisFlag: int = Field(..., description='')
    addToResolutionFlag: int = Field(..., description='')
    emailResourceFlag: int = Field(..., description='')
    emailContactFlag: int = Field(..., description='')
    emailCcFlag: int = Field(..., description='')
    hoursBilled: float = Field(..., description='')
    invoiceHours: float = Field(..., description='')
    hourlyCost: str = Field(..., description='')
    enteredBy: str = Field(..., description='')
    dateEntered: str = Field(..., description='')
    mobileGuid: str = Field(..., description='')
    hourlyRate: float = Field(..., description='')
    agreementHours: float = Field(..., description='')
    agreementAmount: float = Field(..., description='')
    agreementAdjustment: float = Field(..., description='')
    adjustment: float = Field(..., description='')
    invoiceReady: int = Field(..., description='')
    timeSheet: TimeSheetReference = Field(..., description='')
    status: str = Field(..., description='')
    ticket: Ticket = Field(..., description='')
    project: ProjectReference = Field(..., description='')
    phase: PhaseReference = Field(..., description='')
    ticketBoard: str = Field(..., description='')
    ticketStatus: str = Field(..., description='')
    invoiceFlag: int = Field(..., description='')
    extendedInvoiceAmount: float = Field(..., description='')
    locationName: str = Field(..., description='')
    taxCode: TaxCodeReference = Field(..., description='')
