# generated by datamodel-codegen:
#   filename:  tmpsf7kirdr.json
#   timestamp: 2025-05-13T07:46:40+00:00

from __future__ import annotations

import warnings
# Filter Pydantic deprecation warnings for Config options
warnings.filterwarnings("ignore", message="Valid config keys have changed in V2")

from typing import Any, Optional

from pydantic import Field
from sparkdantic import SparkModel

from fabric_api.connectwise_models.reference_model import (
    CompanyReference, LocationReference, SiteReference, 
    BillingTermsReference, CurrencyReference, TaxCodeReference
)


class UnpostedInvoice(SparkModel):
    class Config:
        allow_population_by_field_name = True

    id: int = Field(..., description='')
    billingLogId: int = Field(..., description='')
    locationId: int = Field(..., description='')
    location: LocationReference = Field(..., description='')
    company: CompanyReference = Field(..., description='')
    accountNumber: str = Field(..., description='')
    billToCompany: CompanyReference = Field(..., description='')
    billToSite: SiteReference = Field(..., description='')
    shipToCompany: CompanyReference = Field(..., description='')
    shipToSite: SiteReference = Field(..., description='')
    invoiceNumber: str = Field(..., description='')
    invoiceDate: str = Field(..., description='')
    invoiceType: str = Field(..., description='')
    description: str = Field(..., description='')
    billingTerms: BillingTermsReference = Field(..., description='')
    dueDays: str = Field(..., description='')
    dueDate: str = Field(..., description='')
    currency: CurrencyReference = Field(..., description='')
    subTotal: float = Field(..., description='')
    total: float = Field(..., description='')
    hasTime: int = Field(..., description='')
    hasExpenses: int = Field(..., description='')
    hasProducts: int = Field(..., description='')
    invoiceTaxableFlag: int = Field(..., description='')
    taxCode: TaxCodeReference = Field(..., description='')
    avalaraTaxFlag: int = Field(..., description='')
    itemTaxableFlag: int = Field(..., description='')
    salesTaxAmount: float = Field(..., description='')
    stateTaxFlag: int = Field(..., description='')
    stateTaxAmount: float = Field(..., description='')
    countyTaxFlag: int = Field(..., description='')
    countyTaxAmount: float = Field(..., description='')
    cityTaxFlag: int = Field(..., description='')
    cityTaxAmount: float = Field(..., description='')
    countryTaxFlag: int = Field(..., description='')
    countryTaxAmount: float = Field(..., description='')
    compositeTaxFlag: int = Field(..., description='')
    compositeTaxAmount: float = Field(..., description='')
    levelSixTaxFlag: int = Field(..., description='')
    levelSixTaxAmount: float = Field(..., description='')
    createdBy: str = Field(..., description='')
    dateClosed: str = Field(..., description='')
