"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  CompanyInformation-79.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Companyinformation79(SparkModel):
    PrimaryKey_1: Annotated[str | None, Field(alias='PrimaryKey-1')] = None
    Name_2: Annotated[str | None, Field(alias='Name-2')] = None
    Name2_3: Annotated[str | None, Field(alias='Name2-3')] = None
    Address_4: Annotated[str | None, Field(alias='Address-4')] = None
    Address2_5: Annotated[str | None, Field(alias='Address2-5')] = None
    City_6: Annotated[str | None, Field(alias='City-6')] = None
    PhoneNo_7: Annotated[str | None, Field(alias='PhoneNo-7')] = None
    PhoneNo2_8: Annotated[str | None, Field(alias='PhoneNo2-8')] = None
    TelexNo_9: Annotated[str | None, Field(alias='TelexNo-9')] = None
    FaxNo_10: Annotated[str | None, Field(alias='FaxNo-10')] = None
    GiroNo_11: Annotated[str | None, Field(alias='GiroNo-11')] = None
    BankName_12: Annotated[str | None, Field(alias='BankName-12')] = None
    BankBranchNo_13: Annotated[str | None, Field(alias='BankBranchNo-13')] = None
    BankAccountNo_14: Annotated[str | None, Field(alias='BankAccountNo-14')] = None
    PaymentRoutingNo_15: Annotated[str | None, Field(alias='PaymentRoutingNo-15')] = (
        None
    )
    CustomsPermitNo_17: Annotated[str | None, Field(alias='CustomsPermitNo-17')] = None
    CustomsPermitDate_18: Annotated[str | None, Field(alias='CustomsPermitDate-18')] = (
        None
    )
    VATRegistrationNo_19: Annotated[str | None, Field(alias='VATRegistrationNo-19')] = (
        None
    )
    RegistrationNo_20: Annotated[str | None, Field(alias='RegistrationNo-20')] = None
    TelexAnswerBack_21: Annotated[str | None, Field(alias='TelexAnswerBack-21')] = None
    ShiptoName_22: Annotated[str | None, Field(alias='ShiptoName-22')] = None
    ShiptoName2_23: Annotated[str | None, Field(alias='ShiptoName2-23')] = None
    ShiptoAddress_24: Annotated[str | None, Field(alias='ShiptoAddress-24')] = None
    ShiptoAddress2_25: Annotated[str | None, Field(alias='ShiptoAddress2-25')] = None
    ShiptoCity_26: Annotated[str | None, Field(alias='ShiptoCity-26')] = None
    ShiptoContact_27: Annotated[str | None, Field(alias='ShiptoContact-27')] = None
    LocationCode_28: Annotated[str | None, Field(alias='LocationCode-28')] = None
    PostCode_30: Annotated[str | None, Field(alias='PostCode-30')] = None
    County_31: Annotated[str | None, Field(alias='County-31')] = None
    ShiptoPostCode_32: Annotated[str | None, Field(alias='ShiptoPostCode-32')] = None
    ShiptoCounty_33: Annotated[str | None, Field(alias='ShiptoCounty-33')] = None
    EMail_34: Annotated[str | None, Field(alias='EMail-34')] = None
    HomePage_35: Annotated[str | None, Field(alias='HomePage-35')] = None
    CountryRegionCode_36: Annotated[str | None, Field(alias='CountryRegionCode-36')] = (
        None
    )
    ShiptoCountryRegionCode_37: Annotated[
        str | None, Field(alias='ShiptoCountryRegionCode-37')
    ] = None
    IBAN_38: Annotated[str | None, Field(alias='IBAN-38')] = None
    SWIFTCode_39: Annotated[str | None, Field(alias='SWIFTCode-39')] = None
    IndustrialClassification_40: Annotated[
        str | None, Field(alias='IndustrialClassification-40')
    ] = None
    SystemIndicator_46: Annotated[int | None, Field(alias='SystemIndicator-46')] = None
    CustomSystemIndicatorText_47: Annotated[
        str | None, Field(alias='CustomSystemIndicatorText-47')
    ] = None
    SystemIndicatorStyle_48: Annotated[
        int | None, Field(alias='SystemIndicatorStyle-48')
    ] = None
    AllowBlankPaymentInfo_50: Annotated[
        bool | None, Field(alias='AllowBlankPaymentInfo-50')
    ] = None
    ContactPerson_51: Annotated[str | None, Field(alias='ContactPerson-51')] = None
    GLN_90: Annotated[str | None, Field(alias='GLN-90')] = None
    EORINumber_92: Annotated[str | None, Field(alias='EORINumber-92')] = None
    UseGLNinElectronicDocument_95: Annotated[
        bool | None, Field(alias='UseGLNinElectronicDocument-95')
    ] = None
    PictureLastModDateTime_96: Annotated[
        datetime | None, Field(alias='PictureLastModDateTime-96')
    ] = None
    LastModifiedDateTime_98: Annotated[
        datetime | None, Field(alias='LastModifiedDateTime-98')
    ] = None
    CreatedDateTime_99: Annotated[
        datetime | None, Field(alias='CreatedDateTime-99')
    ] = None
    DemoCompany_100: Annotated[bool | None, Field(alias='DemoCompany-100')] = None
    AlternativeLanguageCode_200: Annotated[
        str | None, Field(alias='AlternativeLanguageCode-200')
    ] = None
    BrandColorValue_300: Annotated[str | None, Field(alias='BrandColorValue-300')] = (
        None
    )
    BrandColorCode_301: Annotated[str | None, Field(alias='BrandColorCode-301')] = None
    ResponsibilityCenter_5700: Annotated[
        str | None, Field(alias='ResponsibilityCenter-5700')
    ] = None
    CheckAvailPeriodCalc_5791: Annotated[
        str | None, Field(alias='CheckAvailPeriodCalc-5791')
    ] = None
    CheckAvailTimeBucket_5792: Annotated[
        int | None, Field(alias='CheckAvailTimeBucket-5792')
    ] = None
    BaseCalendarCode_7600: Annotated[
        str | None, Field(alias='BaseCalendarCode-7600')
    ] = None
    CalConvergenceTimeFrame_7601: Annotated[
        str | None, Field(alias='CalConvergenceTimeFrame-7601')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
