"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Currency-4.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Currency4(SparkModel):
    Code_1: Annotated[str | None, Field(alias='Code-1')] = None
    ISOCode_4: Annotated[str | None, Field(alias='ISOCode-4')] = None
    Description_15: Annotated[str | None, Field(alias='Description-15')] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
