"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  CustLedgerEntry-21.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Custledgerentry21(SparkModel):
    EntryNo_1: Annotated[int | None, Field(alias='EntryNo-1')] = None
    CustomerNo_3: Annotated[str | None, Field(alias='CustomerNo-3')] = None
    PostingDate_4: Annotated[str | None, Field(alias='PostingDate-4')] = None
    DocumentType_5: Annotated[int | None, Field(alias='DocumentType-5')] = None
    DocumentNo_6: Annotated[str | None, Field(alias='DocumentNo-6')] = None
    Description_7: Annotated[str | None, Field(alias='Description-7')] = None
    CustomerName_8: Annotated[str | None, Field(alias='CustomerName-8')] = None
    YourReference_10: Annotated[str | None, Field(alias='YourReference-10')] = None
    CurrencyCode_11: Annotated[str | None, Field(alias='CurrencyCode-11')] = None
    SalesLCY_18: Annotated[float | None, Field(alias='SalesLCY-18')] = None
    ProfitLCY_19: Annotated[float | None, Field(alias='ProfitLCY-19')] = None
    InvDiscountLCY_20: Annotated[float | None, Field(alias='InvDiscountLCY-20')] = None
    SelltoCustomerNo_21: Annotated[str | None, Field(alias='SelltoCustomerNo-21')] = (
        None
    )
    CustomerPostingGroup_22: Annotated[
        str | None, Field(alias='CustomerPostingGroup-22')
    ] = None
    GlobalDimension1Code_23: Annotated[
        str | None, Field(alias='GlobalDimension1Code-23')
    ] = None
    GlobalDimension2Code_24: Annotated[
        str | None, Field(alias='GlobalDimension2Code-24')
    ] = None
    SalespersonCode_25: Annotated[str | None, Field(alias='SalespersonCode-25')] = None
    UserID_27: Annotated[str | None, Field(alias='UserID-27')] = None
    SourceCode_28: Annotated[str | None, Field(alias='SourceCode-28')] = None
    OnHold_33: Annotated[str | None, Field(alias='OnHold-33')] = None
    AppliestoDocType_34: Annotated[int | None, Field(alias='AppliestoDocType-34')] = (
        None
    )
    AppliestoDocNo_35: Annotated[str | None, Field(alias='AppliestoDocNo-35')] = None
    Open_36: Annotated[bool | None, Field(alias='Open-36')] = None
    DueDate_37: Annotated[str | None, Field(alias='DueDate-37')] = None
    PmtDiscountDate_38: Annotated[str | None, Field(alias='PmtDiscountDate-38')] = None
    OriginalPmtDiscPossible_39: Annotated[
        float | None, Field(alias='OriginalPmtDiscPossible-39')
    ] = None
    PmtDiscGivenLCY_40: Annotated[float | None, Field(alias='PmtDiscGivenLCY-40')] = (
        None
    )
    OrigPmtDiscPossibleLCY_42: Annotated[
        float | None, Field(alias='OrigPmtDiscPossibleLCY-42')
    ] = None
    Positive_43: Annotated[bool | None, Field(alias='Positive-43')] = None
    ClosedbyEntryNo_44: Annotated[int | None, Field(alias='ClosedbyEntryNo-44')] = None
    ClosedatDate_45: Annotated[str | None, Field(alias='ClosedatDate-45')] = None
    ClosedbyAmount_46: Annotated[float | None, Field(alias='ClosedbyAmount-46')] = None
    AppliestoID_47: Annotated[str | None, Field(alias='AppliestoID-47')] = None
    JournalTemplName_48: Annotated[str | None, Field(alias='JournalTemplName-48')] = (
        None
    )
    JournalBatchName_49: Annotated[str | None, Field(alias='JournalBatchName-49')] = (
        None
    )
    ReasonCode_50: Annotated[str | None, Field(alias='ReasonCode-50')] = None
    BalAccountType_51: Annotated[int | None, Field(alias='BalAccountType-51')] = None
    BalAccountNo_52: Annotated[str | None, Field(alias='BalAccountNo-52')] = None
    TransactionNo_53: Annotated[int | None, Field(alias='TransactionNo-53')] = None
    ClosedbyAmountLCY_54: Annotated[
        float | None, Field(alias='ClosedbyAmountLCY-54')
    ] = None
    DocumentDate_62: Annotated[str | None, Field(alias='DocumentDate-62')] = None
    ExternalDocumentNo_63: Annotated[
        str | None, Field(alias='ExternalDocumentNo-63')
    ] = None
    CalculateInterest_64: Annotated[
        bool | None, Field(alias='CalculateInterest-64')
    ] = None
    ClosingInterestCalculated_65: Annotated[
        bool | None, Field(alias='ClosingInterestCalculated-65')
    ] = None
    NoSeries_66: Annotated[str | None, Field(alias='NoSeries-66')] = None
    ClosedbyCurrencyCode_67: Annotated[
        str | None, Field(alias='ClosedbyCurrencyCode-67')
    ] = None
    ClosedbyCurrencyAmount_68: Annotated[
        float | None, Field(alias='ClosedbyCurrencyAmount-68')
    ] = None
    AdjustedCurrencyFactor_73: Annotated[
        float | None, Field(alias='AdjustedCurrencyFactor-73')
    ] = None
    OriginalCurrencyFactor_74: Annotated[
        float | None, Field(alias='OriginalCurrencyFactor-74')
    ] = None
    RemainingPmtDiscPossible_77: Annotated[
        float | None, Field(alias='RemainingPmtDiscPossible-77')
    ] = None
    PmtDiscToleranceDate_78: Annotated[
        str | None, Field(alias='PmtDiscToleranceDate-78')
    ] = None
    MaxPaymentTolerance_79: Annotated[
        float | None, Field(alias='MaxPaymentTolerance-79')
    ] = None
    LastIssuedReminderLevel_80: Annotated[
        int | None, Field(alias='LastIssuedReminderLevel-80')
    ] = None
    AcceptedPaymentTolerance_81: Annotated[
        float | None, Field(alias='AcceptedPaymentTolerance-81')
    ] = None
    AcceptedPmtDiscTolerance_82: Annotated[
        bool | None, Field(alias='AcceptedPmtDiscTolerance-82')
    ] = None
    PmtToleranceLCY_83: Annotated[float | None, Field(alias='PmtToleranceLCY-83')] = (
        None
    )
    AmounttoApply_84: Annotated[float | None, Field(alias='AmounttoApply-84')] = None
    ICPartnerCode_85: Annotated[str | None, Field(alias='ICPartnerCode-85')] = None
    ApplyingEntry_86: Annotated[bool | None, Field(alias='ApplyingEntry-86')] = None
    Reversed_87: Annotated[bool | None, Field(alias='Reversed-87')] = None
    ReversedbyEntryNo_88: Annotated[int | None, Field(alias='ReversedbyEntryNo-88')] = (
        None
    )
    ReversedEntryNo_89: Annotated[int | None, Field(alias='ReversedEntryNo-89')] = None
    Prepayment_90: Annotated[bool | None, Field(alias='Prepayment-90')] = None
    PaymentReference_171: Annotated[str | None, Field(alias='PaymentReference-171')] = (
        None
    )
    PaymentMethodCode_172: Annotated[
        str | None, Field(alias='PaymentMethodCode-172')
    ] = None
    AppliestoExtDocNo_173: Annotated[
        str | None, Field(alias='AppliestoExtDocNo-173')
    ] = None
    RecipientBankAccount_288: Annotated[
        str | None, Field(alias='RecipientBankAccount-288')
    ] = None
    MessagetoRecipient_289: Annotated[
        str | None, Field(alias='MessagetoRecipient-289')
    ] = None
    ExportedtoPaymentFile_290: Annotated[
        bool | None, Field(alias='ExportedtoPaymentFile-290')
    ] = None
    DimensionSetID_480: Annotated[int | None, Field(alias='DimensionSetID-480')] = None
    DirectDebitMandateID_1200: Annotated[
        str | None, Field(alias='DirectDebitMandateID-1200')
    ] = None
    PaymentPrediction_1300: Annotated[
        int | None, Field(alias='PaymentPrediction-1300')
    ] = None
    PredictionConfidence_1301: Annotated[
        int | None, Field(alias='PredictionConfidence-1301')
    ] = None
    PredictionConfidence_1302: Annotated[
        float | None, Field(alias='PredictionConfidence-1302')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
