"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Customer-18.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Customer18(SparkModel):
    No_1: Annotated[str | None, Field(alias='No-1')] = None
    Name_2: Annotated[str | None, Field(alias='Name-2')] = None
    Address_5: Annotated[str | None, Field(alias='Address-5')] = None
    Address2_6: Annotated[str | None, Field(alias='Address2-6')] = None
    City_7: Annotated[str | None, Field(alias='City-7')] = None
    Contact_8: Annotated[str | None, Field(alias='Contact-8')] = None
    PhoneNo_9: Annotated[str | None, Field(alias='PhoneNo-9')] = None
    TelexNo_10: Annotated[str | None, Field(alias='TelexNo-10')] = None
    GlobalDimension1Code_16: Annotated[
        str | None, Field(alias='GlobalDimension1Code-16')
    ] = None
    GlobalDimension2Code_17: Annotated[
        str | None, Field(alias='GlobalDimension2Code-17')
    ] = None
    ChainName_18: Annotated[str | None, Field(alias='ChainName-18')] = None
    BudgetedAmount_19: Annotated[float | None, Field(alias='BudgetedAmount-19')] = None
    CreditLimitLCY_20: Annotated[float | None, Field(alias='CreditLimitLCY-20')] = None
    CustomerPostingGroup_21: Annotated[
        str | None, Field(alias='CustomerPostingGroup-21')
    ] = None
    CurrencyCode_22: Annotated[str | None, Field(alias='CurrencyCode-22')] = None
    CustomerPriceGroup_23: Annotated[
        str | None, Field(alias='CustomerPriceGroup-23')
    ] = None
    SalespersonCode_29: Annotated[str | None, Field(alias='SalespersonCode-29')] = None
    CustomerDiscGroup_34: Annotated[str | None, Field(alias='CustomerDiscGroup-34')] = (
        None
    )
    CountryRegionCode_35: Annotated[str | None, Field(alias='CountryRegionCode-35')] = (
        None
    )
    Blocked_39: Annotated[int | None, Field(alias='Blocked-39')] = None
    GenBusPostingGroup_88: Annotated[
        str | None, Field(alias='GenBusPostingGroup-88')
    ] = None
    PostCode_91: Annotated[str | None, Field(alias='PostCode-91')] = None
    County_92: Annotated[str | None, Field(alias='County-92')] = None
    PTEIndustryCode_65001: Annotated[
        str | None, Field(alias='PTEIndustryCode-65001')
    ] = None
    PTEGroupCode_65006: Annotated[str | None, Field(alias='PTEGroupCode-65006')] = None
    PTEGroupingCode_65007: Annotated[
        str | None, Field(alias='PTEGroupingCode-65007')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
