"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  DetailedVendorLedgEntry-380.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Detailedvendorledgentry380(SparkModel):
    EntryNo_1: Annotated[int | None, Field(alias='EntryNo-1')] = None
    VendorLedgerEntryNo_2: Annotated[
        int | None, Field(alias='VendorLedgerEntryNo-2')
    ] = None
    EntryType_3: Annotated[int | None, Field(alias='EntryType-3')] = None
    PostingDate_4: Annotated[str | None, Field(alias='PostingDate-4')] = None
    DocumentType_5: Annotated[int | None, Field(alias='DocumentType-5')] = None
    DocumentNo_6: Annotated[str | None, Field(alias='DocumentNo-6')] = None
    Amount_7: Annotated[float | None, Field(alias='Amount-7')] = None
    AmountLCY_8: Annotated[float | None, Field(alias='AmountLCY-8')] = None
    VendorNo_9: Annotated[str | None, Field(alias='VendorNo-9')] = None
    CurrencyCode_10: Annotated[str | None, Field(alias='CurrencyCode-10')] = None
    SourceCode_12: Annotated[str | None, Field(alias='SourceCode-12')] = None
    TransactionNo_13: Annotated[int | None, Field(alias='TransactionNo-13')] = None
    JournalBatchName_14: Annotated[str | None, Field(alias='JournalBatchName-14')] = (
        None
    )
    ReasonCode_15: Annotated[str | None, Field(alias='ReasonCode-15')] = None
    DebitAmount_16: Annotated[float | None, Field(alias='DebitAmount-16')] = None
    CreditAmount_17: Annotated[float | None, Field(alias='CreditAmount-17')] = None
    DebitAmountLCY_18: Annotated[float | None, Field(alias='DebitAmountLCY-18')] = None
    CreditAmountLCY_19: Annotated[float | None, Field(alias='CreditAmountLCY-19')] = (
        None
    )
    InitialEntryDueDate_20: Annotated[
        str | None, Field(alias='InitialEntryDueDate-20')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
