"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Dimension-348.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Dimension348(SparkModel):
    Code_1: Annotated[str | None, Field(alias='Code-1')] = None
    Name_2: Annotated[str | None, Field(alias='Name-2')] = None
    CodeCaption_3: Annotated[str | None, Field(alias='CodeCaption-3')] = None
    FilterCaption_4: Annotated[str | None, Field(alias='FilterCaption-4')] = None
    Description_5: Annotated[str | None, Field(alias='Description-5')] = None
    Blocked_6: Annotated[bool | None, Field(alias='Blocked-6')] = None
    ConsolidationCode_7: Annotated[str | None, Field(alias='ConsolidationCode-7')] = (
        None
    )
    MaptoICDimensionCode_8: Annotated[
        str | None, Field(alias='MaptoICDimensionCode-8')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
