"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  DimensionValue-349.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Dimensionvalue349(SparkModel):
    DimensionCode_1: Annotated[str | None, Field(alias='DimensionCode-1')] = None
    Code_2: Annotated[str | None, Field(alias='Code-2')] = None
    Name_3: Annotated[str | None, Field(alias='Name-3')] = None
    DimensionValueType_4: Annotated[int | None, Field(alias='DimensionValueType-4')] = (
        None
    )
    Totaling_5: Annotated[str | None, Field(alias='Totaling-5')] = None
    Blocked_6: Annotated[bool | None, Field(alias='Blocked-6')] = None
    ConsolidationCode_7: Annotated[str | None, Field(alias='ConsolidationCode-7')] = (
        None
    )
    Indentation_8: Annotated[int | None, Field(alias='Indentation-8')] = None
    GlobalDimensionNo_9: Annotated[int | None, Field(alias='GlobalDimensionNo-9')] = (
        None
    )
    MaptoICDimensionCode_10: Annotated[
        str | None, Field(alias='MaptoICDimensionCode-10')
    ] = None
    MaptoICDimensionValueCode_11: Annotated[
        str | None, Field(alias='MaptoICDimensionValueCode-11')
    ] = None
    DimensionValueID_12: Annotated[int | None, Field(alias='DimensionValueID-12')] = (
        None
    )
    DimensionId_8002: Annotated[UUID | None, Field(alias='DimensionId-8002')] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
