"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  GeneralLedgerSetup-98.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Generalledgersetup98(SparkModel):
    AdditionalReportingCurrency_68: Annotated[
        str | None, Field(alias='AdditionalReportingCurrency-68')
    ] = None
    LCYCode_71: Annotated[str | None, Field(alias='LCYCode-71')] = None
    ShortcutDimension1Code_81: Annotated[
        str | None, Field(alias='ShortcutDimension1Code-81')
    ] = None
    ShortcutDimension2Code_82: Annotated[
        str | None, Field(alias='ShortcutDimension2Code-82')
    ] = None
    ShortcutDimension3Code_83: Annotated[
        str | None, Field(alias='ShortcutDimension3Code-83')
    ] = None
    ShortcutDimension4Code_84: Annotated[
        str | None, Field(alias='ShortcutDimension4Code-84')
    ] = None
    ShortcutDimension5Code_85: Annotated[
        str | None, Field(alias='ShortcutDimension5Code-85')
    ] = None
    ShortcutDimension6Code_86: Annotated[
        str | None, Field(alias='ShortcutDimension6Code-86')
    ] = None
    ShortcutDimension7Code_87: Annotated[
        str | None, Field(alias='ShortcutDimension7Code-87')
    ] = None
    ShortcutDimension8Code_88: Annotated[
        str | None, Field(alias='ShortcutDimension8Code-88')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
