"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  GLAccount-15.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Glaccount15(SparkModel):
    No_1: Annotated[str | None, Field(alias='No-1')] = None
    Name_2: Annotated[str | None, Field(alias='Name-2')] = None
    SearchName_3: Annotated[str | None, Field(alias='SearchName-3')] = None
    AccountType_4: Annotated[int | None, Field(alias='AccountType-4')] = None
    GlobalDimension1Code_6: Annotated[
        str | None, Field(alias='GlobalDimension1Code-6')
    ] = None
    GlobalDimension2Code_7: Annotated[
        str | None, Field(alias='GlobalDimension2Code-7')
    ] = None
    AccountCategory_8: Annotated[int | None, Field(alias='AccountCategory-8')] = None
    IncomeBalance_9: Annotated[int | None, Field(alias='IncomeBalance-9')] = None
    DebitCredit_10: Annotated[int | None, Field(alias='DebitCredit-10')] = None
    No2_11: Annotated[str | None, Field(alias='No2-11')] = None
    Blocked_13: Annotated[bool | None, Field(alias='Blocked-13')] = None
    DirectPosting_14: Annotated[bool | None, Field(alias='DirectPosting-14')] = None
    ReconciliationAccount_16: Annotated[
        bool | None, Field(alias='ReconciliationAccount-16')
    ] = None
    NewPage_17: Annotated[bool | None, Field(alias='NewPage-17')] = None
    NoofBlankLines_18: Annotated[int | None, Field(alias='NoofBlankLines-18')] = None
    Indentation_19: Annotated[int | None, Field(alias='Indentation-19')] = None
    LastModifiedDateTime_25: Annotated[
        datetime | None, Field(alias='LastModifiedDateTime-25')
    ] = None
    LastDateModified_26: Annotated[str | None, Field(alias='LastDateModified-26')] = (
        None
    )
    Totaling_34: Annotated[str | None, Field(alias='Totaling-34')] = None
    ConsolTranslationMethod_39: Annotated[
        int | None, Field(alias='ConsolTranslationMethod-39')
    ] = None
    ConsolDebitAcc_40: Annotated[str | None, Field(alias='ConsolDebitAcc-40')] = None
    ConsolCreditAcc_41: Annotated[str | None, Field(alias='ConsolCreditAcc-41')] = None
    GenPostingType_43: Annotated[int | None, Field(alias='GenPostingType-43')] = None
    GenBusPostingGroup_44: Annotated[
        str | None, Field(alias='GenBusPostingGroup-44')
    ] = None
    GenProdPostingGroup_45: Annotated[
        str | None, Field(alias='GenProdPostingGroup-45')
    ] = None
    AutomaticExtTexts_49: Annotated[
        bool | None, Field(alias='AutomaticExtTexts-49')
    ] = None
    TaxAreaCode_54: Annotated[str | None, Field(alias='TaxAreaCode-54')] = None
    TaxLiable_55: Annotated[bool | None, Field(alias='TaxLiable-55')] = None
    TaxGroupCode_56: Annotated[str | None, Field(alias='TaxGroupCode-56')] = None
    VATBusPostingGroup_57: Annotated[
        str | None, Field(alias='VATBusPostingGroup-57')
    ] = None
    VATProdPostingGroup_58: Annotated[
        str | None, Field(alias='VATProdPostingGroup-58')
    ] = None
    ExchangeRateAdjustment_63: Annotated[
        int | None, Field(alias='ExchangeRateAdjustment-63')
    ] = None
    DefaultICPartnerGLAccNo_66: Annotated[
        str | None, Field(alias='DefaultICPartnerGLAccNo-66')
    ] = None
    OmitDefaultDescrinJnl_70: Annotated[
        bool | None, Field(alias='OmitDefaultDescrinJnl-70')
    ] = None
    AccountSubcategoryEntryNo_80: Annotated[
        int | None, Field(alias='AccountSubcategoryEntryNo-80')
    ] = None
    CostTypeNo_1100: Annotated[str | None, Field(alias='CostTypeNo-1100')] = None
    DefaultDeferralTemplateCode_1700: Annotated[
        str | None, Field(alias='DefaultDeferralTemplateCode-1700')
    ] = None
    APIAccountType_9000: Annotated[int | None, Field(alias='APIAccountType-9000')] = (
        None
    )
    IRSNumber_10900: Annotated[str | None, Field(alias='IRSNumber-10900')] = None
    IRSNo_14602: Annotated[str | None, Field(alias='IRSNo-14602')] = None
    ReviewPolicy_22200: Annotated[int | None, Field(alias='ReviewPolicy-22200')] = None
    PTENewNo_65000: Annotated[str | None, Field(alias='PTENewNo-65000')] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
