"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  GLEntry-17.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Glentry17(SparkModel):
    EntryNo_1: Annotated[int | None, Field(alias='EntryNo-1')] = None
    GLAccountNo_3: Annotated[str | None, Field(alias='GLAccountNo-3')] = None
    PostingDate_4: Annotated[str | None, Field(alias='PostingDate-4')] = None
    DocumentType_5: Annotated[int | None, Field(alias='DocumentType-5')] = None
    DocumentNo_6: Annotated[str | None, Field(alias='DocumentNo-6')] = None
    Description_7: Annotated[str | None, Field(alias='Description-7')] = None
    BalAccountNo_10: Annotated[str | None, Field(alias='BalAccountNo-10')] = None
    Amount_17: Annotated[float | None, Field(alias='Amount-17')] = None
    GlobalDimension1Code_23: Annotated[
        str | None, Field(alias='GlobalDimension1Code-23')
    ] = None
    GlobalDimension2Code_24: Annotated[
        str | None, Field(alias='GlobalDimension2Code-24')
    ] = None
    UserID_27: Annotated[str | None, Field(alias='UserID-27')] = None
    SourceCode_28: Annotated[str | None, Field(alias='SourceCode-28')] = None
    SystemCreatedEntry_29: Annotated[
        bool | None, Field(alias='SystemCreatedEntry-29')
    ] = None
    PriorYearEntry_30: Annotated[bool | None, Field(alias='PriorYearEntry-30')] = None
    JobNo_41: Annotated[str | None, Field(alias='JobNo-41')] = None
    Quantity_42: Annotated[float | None, Field(alias='Quantity-42')] = None
    VATAmount_43: Annotated[float | None, Field(alias='VATAmount-43')] = None
    BusinessUnitCode_45: Annotated[str | None, Field(alias='BusinessUnitCode-45')] = (
        None
    )
    JournalBatchName_46: Annotated[str | None, Field(alias='JournalBatchName-46')] = (
        None
    )
    ReasonCode_47: Annotated[str | None, Field(alias='ReasonCode-47')] = None
    GenPostingType_48: Annotated[int | None, Field(alias='GenPostingType-48')] = None
    GenBusPostingGroup_49: Annotated[
        str | None, Field(alias='GenBusPostingGroup-49')
    ] = None
    GenProdPostingGroup_50: Annotated[
        str | None, Field(alias='GenProdPostingGroup-50')
    ] = None
    BalAccountType_51: Annotated[int | None, Field(alias='BalAccountType-51')] = None
    TransactionNo_52: Annotated[int | None, Field(alias='TransactionNo-52')] = None
    DebitAmount_53: Annotated[float | None, Field(alias='DebitAmount-53')] = None
    CreditAmount_54: Annotated[float | None, Field(alias='CreditAmount-54')] = None
    DocumentDate_55: Annotated[str | None, Field(alias='DocumentDate-55')] = None
    ExternalDocumentNo_56: Annotated[
        str | None, Field(alias='ExternalDocumentNo-56')
    ] = None
    SourceType_57: Annotated[int | None, Field(alias='SourceType-57')] = None
    SourceNo_58: Annotated[str | None, Field(alias='SourceNo-58')] = None
    NoSeries_59: Annotated[str | None, Field(alias='NoSeries-59')] = None
    TaxAreaCode_60: Annotated[str | None, Field(alias='TaxAreaCode-60')] = None
    TaxLiable_61: Annotated[bool | None, Field(alias='TaxLiable-61')] = None
    TaxGroupCode_62: Annotated[str | None, Field(alias='TaxGroupCode-62')] = None
    UseTax_63: Annotated[bool | None, Field(alias='UseTax-63')] = None
    VATBusPostingGroup_64: Annotated[
        str | None, Field(alias='VATBusPostingGroup-64')
    ] = None
    VATProdPostingGroup_65: Annotated[
        str | None, Field(alias='VATProdPostingGroup-65')
    ] = None
    AdditionalCurrencyAmount_68: Annotated[
        float | None, Field(alias='AdditionalCurrencyAmount-68')
    ] = None
    AddCurrencyDebitAmount_69: Annotated[
        float | None, Field(alias='AddCurrencyDebitAmount-69')
    ] = None
    AddCurrencyCreditAmount_70: Annotated[
        float | None, Field(alias='AddCurrencyCreditAmount-70')
    ] = None
    CloseIncomeStatementDimID_71: Annotated[
        int | None, Field(alias='CloseIncomeStatementDimID-71')
    ] = None
    ICPartnerCode_72: Annotated[str | None, Field(alias='ICPartnerCode-72')] = None
    Reversed_73: Annotated[bool | None, Field(alias='Reversed-73')] = None
    ReversedbyEntryNo_74: Annotated[int | None, Field(alias='ReversedbyEntryNo-74')] = (
        None
    )
    ReversedEntryNo_75: Annotated[int | None, Field(alias='ReversedEntryNo-75')] = None
    JournalTemplName_78: Annotated[str | None, Field(alias='JournalTemplName-78')] = (
        None
    )
    VATReportingDate_79: Annotated[str | None, Field(alias='VATReportingDate-79')] = (
        None
    )
    DimensionSetID_480: Annotated[int | None, Field(alias='DimensionSetID-480')] = None
    LastDimCorrectionEntryNo_495: Annotated[
        int | None, Field(alias='LastDimCorrectionEntryNo-495')
    ] = None
    LastDimCorrectionNode_496: Annotated[
        int | None, Field(alias='LastDimCorrectionNode-496')
    ] = None
    DimensionChangesCount_497: Annotated[
        int | None, Field(alias='DimensionChangesCount-497')
    ] = None
    AllocationAccountNo_2678: Annotated[
        str | None, Field(alias='AllocationAccountNo-2678')
    ] = None
    ProdOrderNo_5400: Annotated[str | None, Field(alias='ProdOrderNo-5400')] = None
    FAEntryType_5600: Annotated[int | None, Field(alias='FAEntryType-5600')] = None
    FAEntryNo_5601: Annotated[int | None, Field(alias='FAEntryNo-5601')] = None
    Comment_5618: Annotated[str | None, Field(alias='Comment-5618')] = None
    NonDeductibleVATAmount_6200: Annotated[
        float | None, Field(alias='NonDeductibleVATAmount-6200')
    ] = None
    NonDeductibleVATAmountACY_6201: Annotated[
        float | None, Field(alias='NonDeductibleVATAmountACY-6201')
    ] = None
    LastModifiedDateTime_8005: Annotated[
        datetime | None, Field(alias='LastModifiedDateTime-8005')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
