"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Item-27.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Item27(SparkModel):
    No_1: Annotated[str | None, Field(alias='No-1')] = None
    Description_3: Annotated[str | None, Field(alias='Description-3')] = None
    Description2_5: Annotated[str | None, Field(alias='Description2-5')] = None
    BaseUnitofMeasure_8: Annotated[str | None, Field(alias='BaseUnitofMeasure-8')] = (
        None
    )
    Type_10: Annotated[int | None, Field(alias='Type-10')] = None
    InventoryPostingGroup_11: Annotated[
        str | None, Field(alias='InventoryPostingGroup-11')
    ] = None
    ItemDiscGroup_14: Annotated[str | None, Field(alias='ItemDiscGroup-14')] = None
    UnitPrice_18: Annotated[float | None, Field(alias='UnitPrice-18')] = None
    UnitCost_22: Annotated[float | None, Field(alias='UnitCost-22')] = None
    VendorNo_31: Annotated[str | None, Field(alias='VendorNo-31')] = None
    VendorItemNo_32: Annotated[str | None, Field(alias='VendorItemNo-32')] = None
    GrossWeight_41: Annotated[float | None, Field(alias='GrossWeight-41')] = None
    NetWeight_42: Annotated[float | None, Field(alias='NetWeight-42')] = None
    UnitVolume_44: Annotated[float | None, Field(alias='UnitVolume-44')] = None
    Blocked_54: Annotated[bool | None, Field(alias='Blocked-54')] = None
    GenProdPostingGroup_91: Annotated[
        str | None, Field(alias='GenProdPostingGroup-91')
    ] = None
    GlobalDimension1Code_105: Annotated[
        str | None, Field(alias='GlobalDimension1Code-105')
    ] = None
    GlobalDimension2Code_106: Annotated[
        str | None, Field(alias='GlobalDimension2Code-106')
    ] = None
    AssemblyPolicy_910: Annotated[int | None, Field(alias='AssemblyPolicy-910')] = None
    ItemCategoryCode_5702: Annotated[
        str | None, Field(alias='ItemCategoryCode-5702')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
