"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Job-167.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Job167(SparkModel):
    No_1: Annotated[str | None, Field(alias='No-1')] = None
    SearchDescription_2: Annotated[str | None, Field(alias='SearchDescription-2')] = (
        None
    )
    Description_3: Annotated[str | None, Field(alias='Description-3')] = None
    Description2_4: Annotated[str | None, Field(alias='Description2-4')] = None
    BilltoCustomerNo_5: Annotated[str | None, Field(alias='BilltoCustomerNo-5')] = None
    CreationDate_12: Annotated[str | None, Field(alias='CreationDate-12')] = None
    StartingDate_13: Annotated[str | None, Field(alias='StartingDate-13')] = None
    EndingDate_14: Annotated[str | None, Field(alias='EndingDate-14')] = None
    Status_19: Annotated[int | None, Field(alias='Status-19')] = None
    PersonResponsible_20: Annotated[str | None, Field(alias='PersonResponsible-20')] = (
        None
    )
    GlobalDimension1Code_21: Annotated[
        str | None, Field(alias='GlobalDimension1Code-21')
    ] = None
    GlobalDimension2Code_22: Annotated[
        str | None, Field(alias='GlobalDimension2Code-22')
    ] = None
    JobPostingGroup_23: Annotated[str | None, Field(alias='JobPostingGroup-23')] = None
    Blocked_24: Annotated[int | None, Field(alias='Blocked-24')] = None
    LastDateModified_29: Annotated[str | None, Field(alias='LastDateModified-29')] = (
        None
    )
    CustomerDiscGroup_31: Annotated[str | None, Field(alias='CustomerDiscGroup-31')] = (
        None
    )
    CustomerPriceGroup_32: Annotated[
        str | None, Field(alias='CustomerPriceGroup-32')
    ] = None
    LanguageCode_41: Annotated[str | None, Field(alias='LanguageCode-41')] = None
    BilltoName_58: Annotated[str | None, Field(alias='BilltoName-58')] = None
    BilltoAddress_59: Annotated[str | None, Field(alias='BilltoAddress-59')] = None
    BilltoAddress2_60: Annotated[str | None, Field(alias='BilltoAddress2-60')] = None
    BilltoCity_61: Annotated[str | None, Field(alias='BilltoCity-61')] = None
    BilltoCounty_63: Annotated[str | None, Field(alias='BilltoCounty-63')] = None
    BilltoPostCode_64: Annotated[str | None, Field(alias='BilltoPostCode-64')] = None
    NoSeries_66: Annotated[str | None, Field(alias='NoSeries-66')] = None
    BilltoCountryRegionCode_67: Annotated[
        str | None, Field(alias='BilltoCountryRegionCode-67')
    ] = None
    BilltoName2_68: Annotated[str | None, Field(alias='BilltoName2-68')] = None
    Reserve_117: Annotated[int | None, Field(alias='Reserve-117')] = None
    WIPMethod_1000: Annotated[str | None, Field(alias='WIPMethod-1000')] = None
    CurrencyCode_1001: Annotated[str | None, Field(alias='CurrencyCode-1001')] = None
    BilltoContactNo_1002: Annotated[str | None, Field(alias='BilltoContactNo-1002')] = (
        None
    )
    BilltoContact_1003: Annotated[str | None, Field(alias='BilltoContact-1003')] = None
    WIPPostingDate_1008: Annotated[str | None, Field(alias='WIPPostingDate-1008')] = (
        None
    )
    InvoiceCurrencyCode_1011: Annotated[
        str | None, Field(alias='InvoiceCurrencyCode-1011')
    ] = None
    ExchCalculationCost_1012: Annotated[
        int | None, Field(alias='ExchCalculationCost-1012')
    ] = None
    ExchCalculationPrice_1013: Annotated[
        int | None, Field(alias='ExchCalculationPrice-1013')
    ] = None
    AllowScheduleContractLines_1014: Annotated[
        bool | None, Field(alias='AllowScheduleContractLines-1014')
    ] = None
    Complete_1015: Annotated[bool | None, Field(alias='Complete-1015')] = None
    ApplyUsageLink_1025: Annotated[bool | None, Field(alias='ApplyUsageLink-1025')] = (
        None
    )
    WIPPostingMethod_1027: Annotated[
        int | None, Field(alias='WIPPostingMethod-1027')
    ] = None
    OverBudget_1035: Annotated[bool | None, Field(alias='OverBudget-1035')] = None
    ProjectManager_1036: Annotated[str | None, Field(alias='ProjectManager-1036')] = (
        None
    )
    SelltoCustomerNo_2000: Annotated[
        str | None, Field(alias='SelltoCustomerNo-2000')
    ] = None
    SelltoCustomerName_2001: Annotated[
        str | None, Field(alias='SelltoCustomerName-2001')
    ] = None
    SelltoCustomerName2_2002: Annotated[
        str | None, Field(alias='SelltoCustomerName2-2002')
    ] = None
    SelltoAddress_2003: Annotated[str | None, Field(alias='SelltoAddress-2003')] = None
    SelltoAddress2_2004: Annotated[str | None, Field(alias='SelltoAddress2-2004')] = (
        None
    )
    SelltoCity_2005: Annotated[str | None, Field(alias='SelltoCity-2005')] = None
    SelltoContact_2006: Annotated[str | None, Field(alias='SelltoContact-2006')] = None
    SelltoPostCode_2007: Annotated[str | None, Field(alias='SelltoPostCode-2007')] = (
        None
    )
    SelltoCounty_2008: Annotated[str | None, Field(alias='SelltoCounty-2008')] = None
    SelltoCountryRegionCode_2009: Annotated[
        str | None, Field(alias='SelltoCountryRegionCode-2009')
    ] = None
    SelltoPhoneNo_2010: Annotated[str | None, Field(alias='SelltoPhoneNo-2010')] = None
    SelltoEMail_2011: Annotated[str | None, Field(alias='SelltoEMail-2011')] = None
    SelltoContactNo_2012: Annotated[str | None, Field(alias='SelltoContactNo-2012')] = (
        None
    )
    ShiptoCode_3000: Annotated[str | None, Field(alias='ShiptoCode-3000')] = None
    ShiptoName_3001: Annotated[str | None, Field(alias='ShiptoName-3001')] = None
    ShiptoName2_3002: Annotated[str | None, Field(alias='ShiptoName2-3002')] = None
    ShiptoAddress_3003: Annotated[str | None, Field(alias='ShiptoAddress-3003')] = None
    ShiptoAddress2_3004: Annotated[str | None, Field(alias='ShiptoAddress2-3004')] = (
        None
    )
    ShiptoCity_3005: Annotated[str | None, Field(alias='ShiptoCity-3005')] = None
    ShiptoContact_3006: Annotated[str | None, Field(alias='ShiptoContact-3006')] = None
    ShiptoPostCode_3007: Annotated[str | None, Field(alias='ShiptoPostCode-3007')] = (
        None
    )
    ShiptoCounty_3008: Annotated[str | None, Field(alias='ShiptoCounty-3008')] = None
    ShiptoCountryRegionCode_3009: Annotated[
        str | None, Field(alias='ShiptoCountryRegionCode-3009')
    ] = None
    ExternalDocumentNo_4000: Annotated[
        str | None, Field(alias='ExternalDocumentNo-4000')
    ] = None
    PaymentMethodCode_4001: Annotated[
        str | None, Field(alias='PaymentMethodCode-4001')
    ] = None
    PaymentTermsCode_4002: Annotated[
        str | None, Field(alias='PaymentTermsCode-4002')
    ] = None
    YourReference_4003: Annotated[str | None, Field(alias='YourReference-4003')] = None
    PriceCalculationMethod_7000: Annotated[
        int | None, Field(alias='PriceCalculationMethod-7000')
    ] = None
    CostCalculationMethod_7001: Annotated[
        int | None, Field(alias='CostCalculationMethod-7001')
    ] = None
    PTEGroupCode_65000: Annotated[str | None, Field(alias='PTEGroupCode-65000')] = None
    PTEForbidtoReopenJobReq_65001: Annotated[
        bool | None, Field(alias='PTEForbidtoReopenJobReq-65001')
    ] = None
    PTETempoID_65002: Annotated[str | None, Field(alias='PTETempoID-65002')] = None
    PTEJiraPrimaryProjectId_65003: Annotated[
        int | None, Field(alias='PTEJiraPrimaryProjectId-65003')
    ] = None
    PTETransactionReportssur_65004: Annotated[
        bool | None, Field(alias='PTETransactionReportssur-65004')
    ] = None
    PTECategory_65005: Annotated[str | None, Field(alias='PTECategory-65005')] = None
    PTEJobRequestRequired_65006: Annotated[
        bool | None, Field(alias='PTEJobRequestRequired-65006')
    ] = None
    WJOBNamedEmployees_10007200: Annotated[
        bool | None, Field(alias='WJOBNamedEmployees-10007200')
    ] = None
    WJOBRSMReport_10007203: Annotated[
        int | None, Field(alias='WJOBRSMReport-10007203')
    ] = None
    WJOBRSMReportTable_10007204: Annotated[
        int | None, Field(alias='WJOBRSMReportTable-10007204')
    ] = None
    WJOBTemplate_10007208: Annotated[
        bool | None, Field(alias='WJOBTemplate-10007208')
    ] = None
    WJOBType_10007209: Annotated[str | None, Field(alias='WJOBType-10007209')] = None
    WJOBWorkTypeCode_10007211: Annotated[
        str | None, Field(alias='WJOBWorkTypeCode-10007211')
    ] = None
    WJOBRSMCombine_10007212: Annotated[
        int | None, Field(alias='WJOBRSMCombine-10007212')
    ] = None
    WJOBScheduleisalsoContract_10007218: Annotated[
        bool | None, Field(alias='WJOBScheduleisalsoContract-10007218')
    ] = None
    WJOBCreateSchedulewhenPoste_10007219: Annotated[
        bool | None, Field(alias='WJOBCreateSchedulewhenPoste-10007219')
    ] = None
    WJOBMaxHoursWarning_10007220: Annotated[
        bool | None, Field(alias='WJOBMaxHoursWarning-10007220')
    ] = None
    WJOBSupervisor_10007221: Annotated[
        str | None, Field(alias='WJOBSupervisor-10007221')
    ] = None
    WJOBVATBusPostingGroup_10007222: Annotated[
        str | None, Field(alias='WJOBVATBusPostingGroup-10007222')
    ] = None
    WJOBJournalsReviewedDate_10007223: Annotated[
        str | None, Field(alias='WJOBJournalsReviewedDate-10007223')
    ] = None
    WJOBCreatedby_10007225: Annotated[
        str | None, Field(alias='WJOBCreatedby-10007225')
    ] = None
    WJOBLastModifiedby_10007226: Annotated[
        str | None, Field(alias='WJOBLastModifiedby-10007226')
    ] = None
    WJOBShiptoCode_10007249: Annotated[
        str | None, Field(alias='WJOBShiptoCode-10007249')
    ] = None
    WJobPAInvoiceMaxhours_10007251: Annotated[
        float | None, Field(alias='WJobPAInvoiceMaxhours-10007251')
    ] = None
    WJobPAInvoiceMaxAmount_10007252: Annotated[
        float | None, Field(alias='WJobPAInvoiceMaxAmount-10007252')
    ] = None
    WJobPADiscountLimitAmt_10007253: Annotated[
        float | None, Field(alias='WJobPADiscountLimitAmt-10007253')
    ] = None
    WJobPAExcLimitDiscount_10007254: Annotated[
        float | None, Field(alias='WJobPAExcLimitDiscount-10007254')
    ] = None
    WJobPAProformaperTask_10007256: Annotated[
        bool | None, Field(alias='WJobPAProformaperTask-10007256')
    ] = None
    WJobPAIndexCode_10007258: Annotated[
        str | None, Field(alias='WJobPAIndexCode-10007258')
    ] = None
    WJobPAContractRefIndex_10007259: Annotated[
        float | None, Field(alias='WJobPAContractRefIndex-10007259')
    ] = None
    WJobJRJobRequestsRequired_10007270: Annotated[
        bool | None, Field(alias='WJobJRJobRequestsRequired-10007270')
    ] = None
    WJOBShowonTransactionReport_10007550: Annotated[
        int | None, Field(alias='WJOBShowonTransactionReport-10007550')
    ] = None
    WJOBTransactionGrouping_10007551: Annotated[
        int | None, Field(alias='WJOBTransactionGrouping-10007551')
    ] = None
    WJobPABilltoJobNo_10027451: Annotated[
        str | None, Field(alias='WJobPABilltoJobNo-10027451')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
