"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  JobLedgerEntry-169.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Jobledgerentry169(SparkModel):
    EntryNo_1: Annotated[int | None, Field(alias='EntryNo-1')] = None
    JobNo_2: Annotated[str | None, Field(alias='JobNo-2')] = None
    PostingDate_3: Annotated[str | None, Field(alias='PostingDate-3')] = None
    DocumentNo_4: Annotated[str | None, Field(alias='DocumentNo-4')] = None
    Type_5: Annotated[int | None, Field(alias='Type-5')] = None
    No_7: Annotated[str | None, Field(alias='No-7')] = None
    Description_8: Annotated[str | None, Field(alias='Description-8')] = None
    Quantity_9: Annotated[float | None, Field(alias='Quantity-9')] = None
    DirectUnitCostLCY_11: Annotated[
        float | None, Field(alias='DirectUnitCostLCY-11')
    ] = None
    UnitCostLCY_12: Annotated[float | None, Field(alias='UnitCostLCY-12')] = None
    TotalCostLCY_13: Annotated[float | None, Field(alias='TotalCostLCY-13')] = None
    UnitPriceLCY_14: Annotated[float | None, Field(alias='UnitPriceLCY-14')] = None
    TotalPriceLCY_15: Annotated[float | None, Field(alias='TotalPriceLCY-15')] = None
    ResourceGroupNo_16: Annotated[str | None, Field(alias='ResourceGroupNo-16')] = None
    UnitofMeasureCode_17: Annotated[str | None, Field(alias='UnitofMeasureCode-17')] = (
        None
    )
    LocationCode_20: Annotated[str | None, Field(alias='LocationCode-20')] = None
    JobPostingGroup_29: Annotated[str | None, Field(alias='JobPostingGroup-29')] = None
    GlobalDimension1Code_30: Annotated[
        str | None, Field(alias='GlobalDimension1Code-30')
    ] = None
    GlobalDimension2Code_31: Annotated[
        str | None, Field(alias='GlobalDimension2Code-31')
    ] = None
    WorkTypeCode_32: Annotated[str | None, Field(alias='WorkTypeCode-32')] = None
    CustomerPriceGroup_33: Annotated[
        str | None, Field(alias='CustomerPriceGroup-33')
    ] = None
    UserID_37: Annotated[str | None, Field(alias='UserID-37')] = None
    SourceCode_38: Annotated[str | None, Field(alias='SourceCode-38')] = None
    ShptMethodCode_40: Annotated[str | None, Field(alias='ShptMethodCode-40')] = None
    AmttoPosttoGL_60: Annotated[float | None, Field(alias='AmttoPosttoGL-60')] = None
    AmtPostedtoGL_61: Annotated[float | None, Field(alias='AmtPostedtoGL-61')] = None
    EntryType_64: Annotated[int | None, Field(alias='EntryType-64')] = None
    JournalBatchName_75: Annotated[str | None, Field(alias='JournalBatchName-75')] = (
        None
    )
    ReasonCode_76: Annotated[str | None, Field(alias='ReasonCode-76')] = None
    TransactionType_77: Annotated[str | None, Field(alias='TransactionType-77')] = None
    TransportMethod_78: Annotated[str | None, Field(alias='TransportMethod-78')] = None
    CountryRegionCode_79: Annotated[str | None, Field(alias='CountryRegionCode-79')] = (
        None
    )
    GenBusPostingGroup_80: Annotated[
        str | None, Field(alias='GenBusPostingGroup-80')
    ] = None
    GenProdPostingGroup_81: Annotated[
        str | None, Field(alias='GenProdPostingGroup-81')
    ] = None
    EntryExitPoint_82: Annotated[str | None, Field(alias='EntryExitPoint-82')] = None
    DocumentDate_83: Annotated[str | None, Field(alias='DocumentDate-83')] = None
    ExternalDocumentNo_84: Annotated[
        str | None, Field(alias='ExternalDocumentNo-84')
    ] = None
    Area_85: Annotated[str | None, Field(alias='Area-85')] = None
    TransactionSpecification_86: Annotated[
        str | None, Field(alias='TransactionSpecification-86')
    ] = None
    NoSeries_87: Annotated[str | None, Field(alias='NoSeries-87')] = None
    AdditionalCurrencyTotalCost_88: Annotated[
        float | None, Field(alias='AdditionalCurrencyTotalCost-88')
    ] = None
    AddCurrencyTotalPrice_89: Annotated[
        float | None, Field(alias='AddCurrencyTotalPrice-89')
    ] = None
    AddCurrencyLineAmount_94: Annotated[
        float | None, Field(alias='AddCurrencyLineAmount-94')
    ] = None
    DimensionSetID_480: Annotated[int | None, Field(alias='DimensionSetID-480')] = None
    JobTaskNo_1000: Annotated[str | None, Field(alias='JobTaskNo-1000')] = None
    LineAmountLCY_1001: Annotated[float | None, Field(alias='LineAmountLCY-1001')] = (
        None
    )
    UnitCost_1002: Annotated[float | None, Field(alias='UnitCost-1002')] = None
    TotalCost_1003: Annotated[float | None, Field(alias='TotalCost-1003')] = None
    UnitPrice_1004: Annotated[float | None, Field(alias='UnitPrice-1004')] = None
    TotalPrice_1005: Annotated[float | None, Field(alias='TotalPrice-1005')] = None
    LineAmount_1006: Annotated[float | None, Field(alias='LineAmount-1006')] = None
    LineDiscountAmount_1007: Annotated[
        float | None, Field(alias='LineDiscountAmount-1007')
    ] = None
    LineDiscountAmountLCY_1008: Annotated[
        float | None, Field(alias='LineDiscountAmountLCY-1008')
    ] = None
    CurrencyCode_1009: Annotated[str | None, Field(alias='CurrencyCode-1009')] = None
    CurrencyFactor_1010: Annotated[float | None, Field(alias='CurrencyFactor-1010')] = (
        None
    )
    Description2_1016: Annotated[str | None, Field(alias='Description2-1016')] = None
    LedgerEntryType_1017: Annotated[int | None, Field(alias='LedgerEntryType-1017')] = (
        None
    )
    LedgerEntryNo_1018: Annotated[int | None, Field(alias='LedgerEntryNo-1018')] = None
    SerialNo_1019: Annotated[str | None, Field(alias='SerialNo-1019')] = None
    LotNo_1020: Annotated[str | None, Field(alias='LotNo-1020')] = None
    LineDiscount_1021: Annotated[float | None, Field(alias='LineDiscount-1021')] = None
    LineType_1022: Annotated[int | None, Field(alias='LineType-1022')] = None
    OriginalUnitCostLCY_1023: Annotated[
        float | None, Field(alias='OriginalUnitCostLCY-1023')
    ] = None
    OriginalTotalCostLCY_1024: Annotated[
        float | None, Field(alias='OriginalTotalCostLCY-1024')
    ] = None
    OriginalUnitCost_1025: Annotated[
        float | None, Field(alias='OriginalUnitCost-1025')
    ] = None
    OriginalTotalCost_1026: Annotated[
        float | None, Field(alias='OriginalTotalCost-1026')
    ] = None
    OriginalTotalCostACY_1027: Annotated[
        float | None, Field(alias='OriginalTotalCostACY-1027')
    ] = None
    Adjusted_1028: Annotated[bool | None, Field(alias='Adjusted-1028')] = None
    DateTimeAdjusted_1029: Annotated[
        datetime | None, Field(alias='DateTimeAdjusted-1029')
    ] = None
    VariantCode_5402: Annotated[str | None, Field(alias='VariantCode-5402')] = None
    BinCode_5403: Annotated[str | None, Field(alias='BinCode-5403')] = None
    QtyperUnitofMeasure_5404: Annotated[
        float | None, Field(alias='QtyperUnitofMeasure-5404')
    ] = None
    QuantityBase_5405: Annotated[float | None, Field(alias='QuantityBase-5405')] = None
    ServiceOrderNo_5900: Annotated[str | None, Field(alias='ServiceOrderNo-5900')] = (
        None
    )
    PostedServiceShipmentNo_5901: Annotated[
        str | None, Field(alias='PostedServiceShipmentNo-5901')
    ] = None
    PackageNo_6515: Annotated[str | None, Field(alias='PackageNo-6515')] = None
    PTEOldPhaseCode_65000: Annotated[
        str | None, Field(alias='PTEOldPhaseCode-65000')
    ] = None
    PTEJobAnalyzesType_65001: Annotated[
        int | None, Field(alias='PTEJobAnalyzesType-65001')
    ] = None
    PTECustomerNo_65002: Annotated[str | None, Field(alias='PTECustomerNo-65002')] = (
        None
    )
    PTECustomerName_65003: Annotated[
        str | None, Field(alias='PTECustomerName-65003')
    ] = None
    PTEEmployeeDivision_65004: Annotated[
        str | None, Field(alias='PTEEmployeeDivision-65004')
    ] = None
    PTEJiraWorklogid_65005: Annotated[
        int | None, Field(alias='PTEJiraWorklogid-65005')
    ] = None
    PTEDescription3_65020: Annotated[
        str | None, Field(alias='PTEDescription3-65020')
    ] = None
    WJOBReviewedby_10007200: Annotated[
        str | None, Field(alias='WJOBReviewedby-10007200')
    ] = None
    WJOBWork_10007201: Annotated[bool | None, Field(alias='WJOBWork-10007201')] = None
    WJOBJobType_10007202: Annotated[str | None, Field(alias='WJOBJobType-10007202')] = (
        None
    )
    WJOBManuallyModified_10007203: Annotated[
        bool | None, Field(alias='WJOBManuallyModified-10007203')
    ] = None
    WJOBReviewed_10007204: Annotated[
        bool | None, Field(alias='WJOBReviewed-10007204')
    ] = None
    WJOBRegbyResource_10007206: Annotated[
        str | None, Field(alias='WJOBRegbyResource-10007206')
    ] = None
    WJOBResourceName_10007208: Annotated[
        str | None, Field(alias='WJOBResourceName-10007208')
    ] = None
    WJobExternalDocument2_10007210: Annotated[
        str | None, Field(alias='WJobExternalDocument2-10007210')
    ] = None
    WJobPAProformaNo_10007255: Annotated[
        str | None, Field(alias='WJobPAProformaNo-10007255')
    ] = None
    WJobJRRequestNo_10007270: Annotated[
        str | None, Field(alias='WJobJRRequestNo-10007270')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
