"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Resource-156.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Resource156(SparkModel):
    No_1: Annotated[str | None, Field(alias='No-1')] = None
    Type_2: Annotated[int | None, Field(alias='Type-2')] = None
    Name_3: Annotated[str | None, Field(alias='Name-3')] = None
    Name2_5: Annotated[str | None, Field(alias='Name2-5')] = None
    Address_6: Annotated[str | None, Field(alias='Address-6')] = None
    Address2_7: Annotated[str | None, Field(alias='Address2-7')] = None
    City_8: Annotated[str | None, Field(alias='City-8')] = None
    SocialSecurityNo_9: Annotated[str | None, Field(alias='SocialSecurityNo-9')] = None
    JobTitle_10: Annotated[str | None, Field(alias='JobTitle-10')] = None
    Education_11: Annotated[str | None, Field(alias='Education-11')] = None
    EmploymentDate_13: Annotated[str | None, Field(alias='EmploymentDate-13')] = None
    ResourceGroupNo_14: Annotated[str | None, Field(alias='ResourceGroupNo-14')] = None
    GlobalDimension1Code_16: Annotated[
        str | None, Field(alias='GlobalDimension1Code-16')
    ] = None
    GlobalDimension2Code_17: Annotated[
        str | None, Field(alias='GlobalDimension2Code-17')
    ] = None
    BaseUnitofMeasure_18: Annotated[str | None, Field(alias='BaseUnitofMeasure-18')] = (
        None
    )
    DirectUnitCost_19: Annotated[float | None, Field(alias='DirectUnitCost-19')] = None
    UnitCost_21: Annotated[float | None, Field(alias='UnitCost-21')] = None
    UnitPrice_24: Annotated[float | None, Field(alias='UnitPrice-24')] = None
    VendorNo_25: Annotated[str | None, Field(alias='VendorNo-25')] = None
    Blocked_38: Annotated[bool | None, Field(alias='Blocked-38')] = None
    GenProdPostingGroup_51: Annotated[
        str | None, Field(alias='GenProdPostingGroup-51')
    ] = None
    PostCode_53: Annotated[str | None, Field(alias='PostCode-53')] = None
    County_54: Annotated[str | None, Field(alias='County-54')] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
