"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  SalesInvoiceLine-113.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Salesinvoiceline113(SparkModel):
    SelltoCustomerNo_2: Annotated[str | None, Field(alias='SelltoCustomerNo-2')] = None
    DocumentNo_3: Annotated[str | None, Field(alias='DocumentNo-3')] = None
    LineNo_4: Annotated[int | None, Field(alias='LineNo-4')] = None
    Type_5: Annotated[int | None, Field(alias='Type-5')] = None
    No_6: Annotated[str | None, Field(alias='No-6')] = None
    LocationCode_7: Annotated[str | None, Field(alias='LocationCode-7')] = None
    PostingGroup_8: Annotated[str | None, Field(alias='PostingGroup-8')] = None
    ShipmentDate_10: Annotated[str | None, Field(alias='ShipmentDate-10')] = None
    Description_11: Annotated[str | None, Field(alias='Description-11')] = None
    Description2_12: Annotated[str | None, Field(alias='Description2-12')] = None
    UnitofMeasure_13: Annotated[str | None, Field(alias='UnitofMeasure-13')] = None
    Quantity_15: Annotated[float | None, Field(alias='Quantity-15')] = None
    UnitPrice_22: Annotated[float | None, Field(alias='UnitPrice-22')] = None
    UnitCostLCY_23: Annotated[float | None, Field(alias='UnitCostLCY-23')] = None
    VAT_25: Annotated[float | None, Field(alias='VAT-25')] = None
    LineDiscount_27: Annotated[float | None, Field(alias='LineDiscount-27')] = None
    LineDiscountAmount_28: Annotated[
        float | None, Field(alias='LineDiscountAmount-28')
    ] = None
    Amount_29: Annotated[float | None, Field(alias='Amount-29')] = None
    AmountIncludingVAT_30: Annotated[
        float | None, Field(alias='AmountIncludingVAT-30')
    ] = None
    AllowInvoiceDisc_32: Annotated[bool | None, Field(alias='AllowInvoiceDisc-32')] = (
        None
    )
    GrossWeight_34: Annotated[float | None, Field(alias='GrossWeight-34')] = None
    NetWeight_35: Annotated[float | None, Field(alias='NetWeight-35')] = None
    UnitsperParcel_36: Annotated[float | None, Field(alias='UnitsperParcel-36')] = None
    UnitVolume_37: Annotated[float | None, Field(alias='UnitVolume-37')] = None
    AppltoItemEntry_38: Annotated[int | None, Field(alias='AppltoItemEntry-38')] = None
    ShortcutDimension1Code_40: Annotated[
        str | None, Field(alias='ShortcutDimension1Code-40')
    ] = None
    ShortcutDimension2Code_41: Annotated[
        str | None, Field(alias='ShortcutDimension2Code-41')
    ] = None
    CustomerPriceGroup_42: Annotated[
        str | None, Field(alias='CustomerPriceGroup-42')
    ] = None
    JobNo_45: Annotated[str | None, Field(alias='JobNo-45')] = None
    WorkTypeCode_52: Annotated[str | None, Field(alias='WorkTypeCode-52')] = None
    ShipmentNo_63: Annotated[str | None, Field(alias='ShipmentNo-63')] = None
    ShipmentLineNo_64: Annotated[int | None, Field(alias='ShipmentLineNo-64')] = None
    OrderNo_65: Annotated[str | None, Field(alias='OrderNo-65')] = None
    OrderLineNo_66: Annotated[int | None, Field(alias='OrderLineNo-66')] = None
    BilltoCustomerNo_68: Annotated[str | None, Field(alias='BilltoCustomerNo-68')] = (
        None
    )
    InvDiscountAmount_69: Annotated[
        float | None, Field(alias='InvDiscountAmount-69')
    ] = None
    DropShipment_73: Annotated[bool | None, Field(alias='DropShipment-73')] = None
    GenBusPostingGroup_74: Annotated[
        str | None, Field(alias='GenBusPostingGroup-74')
    ] = None
    GenProdPostingGroup_75: Annotated[
        str | None, Field(alias='GenProdPostingGroup-75')
    ] = None
    VATCalculationType_77: Annotated[
        int | None, Field(alias='VATCalculationType-77')
    ] = None
    TransactionType_78: Annotated[str | None, Field(alias='TransactionType-78')] = None
    TransportMethod_79: Annotated[str | None, Field(alias='TransportMethod-79')] = None
    AttachedtoLineNo_80: Annotated[int | None, Field(alias='AttachedtoLineNo-80')] = (
        None
    )
    ExitPoint_81: Annotated[str | None, Field(alias='ExitPoint-81')] = None
    Area_82: Annotated[str | None, Field(alias='Area-82')] = None
    TransactionSpecification_83: Annotated[
        str | None, Field(alias='TransactionSpecification-83')
    ] = None
    TaxCategory_84: Annotated[str | None, Field(alias='TaxCategory-84')] = None
    TaxAreaCode_85: Annotated[str | None, Field(alias='TaxAreaCode-85')] = None
    TaxLiable_86: Annotated[bool | None, Field(alias='TaxLiable-86')] = None
    TaxGroupCode_87: Annotated[str | None, Field(alias='TaxGroupCode-87')] = None
    VATClauseCode_88: Annotated[str | None, Field(alias='VATClauseCode-88')] = None
    VATBusPostingGroup_89: Annotated[
        str | None, Field(alias='VATBusPostingGroup-89')
    ] = None
    VATProdPostingGroup_90: Annotated[
        str | None, Field(alias='VATProdPostingGroup-90')
    ] = None
    BlanketOrderNo_97: Annotated[str | None, Field(alias='BlanketOrderNo-97')] = None
    BlanketOrderLineNo_98: Annotated[
        int | None, Field(alias='BlanketOrderLineNo-98')
    ] = None
    VATBaseAmount_99: Annotated[float | None, Field(alias='VATBaseAmount-99')] = None
    UnitCost_100: Annotated[float | None, Field(alias='UnitCost-100')] = None
    SystemCreatedEntry_101: Annotated[
        bool | None, Field(alias='SystemCreatedEntry-101')
    ] = None
    LineAmount_103: Annotated[float | None, Field(alias='LineAmount-103')] = None
    VATDifference_104: Annotated[float | None, Field(alias='VATDifference-104')] = None
    VATIdentifier_106: Annotated[str | None, Field(alias='VATIdentifier-106')] = None
    ICPartnerRefType_107: Annotated[int | None, Field(alias='ICPartnerRefType-107')] = (
        None
    )
    ICPartnerReference_108: Annotated[
        str | None, Field(alias='ICPartnerReference-108')
    ] = None
    PrepaymentLine_123: Annotated[bool | None, Field(alias='PrepaymentLine-123')] = None
    ICPartnerCode_130: Annotated[str | None, Field(alias='ICPartnerCode-130')] = None
    PostingDate_131: Annotated[str | None, Field(alias='PostingDate-131')] = None
    ICItemReferenceNo_138: Annotated[
        str | None, Field(alias='ICItemReferenceNo-138')
    ] = None
    PmtDiscountAmount_145: Annotated[
        float | None, Field(alias='PmtDiscountAmount-145')
    ] = None
    LineDiscountCalculation_180: Annotated[
        int | None, Field(alias='LineDiscountCalculation-180')
    ] = None
    DimensionSetID_480: Annotated[int | None, Field(alias='DimensionSetID-480')] = None
    JobTaskNo_1001: Annotated[str | None, Field(alias='JobTaskNo-1001')] = None
    JobContractEntryNo_1002: Annotated[
        int | None, Field(alias='JobContractEntryNo-1002')
    ] = None
    DeferralCode_1700: Annotated[str | None, Field(alias='DeferralCode-1700')] = None
    AllocationAccountNo_2678: Annotated[
        str | None, Field(alias='AllocationAccountNo-2678')
    ] = None
    VariantCode_5402: Annotated[str | None, Field(alias='VariantCode-5402')] = None
    BinCode_5403: Annotated[str | None, Field(alias='BinCode-5403')] = None
    QtyperUnitofMeasure_5404: Annotated[
        float | None, Field(alias='QtyperUnitofMeasure-5404')
    ] = None
    UnitofMeasureCode_5407: Annotated[
        str | None, Field(alias='UnitofMeasureCode-5407')
    ] = None
    QuantityBase_5415: Annotated[float | None, Field(alias='QuantityBase-5415')] = None
    FAPostingDate_5600: Annotated[str | None, Field(alias='FAPostingDate-5600')] = None
    DepreciationBookCode_5602: Annotated[
        str | None, Field(alias='DepreciationBookCode-5602')
    ] = None
    DepruntilFAPostingDate_5605: Annotated[
        bool | None, Field(alias='DepruntilFAPostingDate-5605')
    ] = None
    DuplicateinDepreciationBook_5612: Annotated[
        str | None, Field(alias='DuplicateinDepreciationBook-5612')
    ] = None
    UseDuplicationList_5613: Annotated[
        bool | None, Field(alias='UseDuplicationList-5613')
    ] = None
    ResponsibilityCenter_5700: Annotated[
        str | None, Field(alias='ResponsibilityCenter-5700')
    ] = None
    ItemCategoryCode_5709: Annotated[
        str | None, Field(alias='ItemCategoryCode-5709')
    ] = None
    Nonstock_5710: Annotated[bool | None, Field(alias='Nonstock-5710')] = None
    PurchasingCode_5711: Annotated[str | None, Field(alias='PurchasingCode-5711')] = (
        None
    )
    ItemReferenceNo_5725: Annotated[str | None, Field(alias='ItemReferenceNo-5725')] = (
        None
    )
    ItemReferenceUnitofMeasure_5726: Annotated[
        str | None, Field(alias='ItemReferenceUnitofMeasure-5726')
    ] = None
    ItemReferenceType_5727: Annotated[
        int | None, Field(alias='ItemReferenceType-5727')
    ] = None
    ItemReferenceTypeNo_5728: Annotated[
        str | None, Field(alias='ItemReferenceTypeNo-5728')
    ] = None
    ApplfromItemEntry_5811: Annotated[
        int | None, Field(alias='ApplfromItemEntry-5811')
    ] = None
    ReturnReasonCode_6608: Annotated[
        str | None, Field(alias='ReturnReasonCode-6608')
    ] = None
    PriceCalculationMethod_7000: Annotated[
        int | None, Field(alias='PriceCalculationMethod-7000')
    ] = None
    AllowLineDisc_7001: Annotated[bool | None, Field(alias='AllowLineDisc-7001')] = None
    CustomerDiscGroup_7002: Annotated[
        str | None, Field(alias='CustomerDiscGroup-7002')
    ] = None
    Pricedescription_7004: Annotated[
        str | None, Field(alias='Pricedescription-7004')
    ] = None
    ShpfyOrderLineId_30100: Annotated[
        int | None, Field(alias='ShpfyOrderLineId-30100')
    ] = None
    ShpfyOrderNo_30101: Annotated[str | None, Field(alias='ShpfyOrderNo-30101')] = None
    PTEDescription3_65008: Annotated[
        str | None, Field(alias='PTEDescription3-65008')
    ] = None
    AMSAgreementNo_10007050: Annotated[
        str | None, Field(alias='AMSAgreementNo-10007050')
    ] = None
    AMSIndex_10007051: Annotated[str | None, Field(alias='AMSIndex-10007051')] = None
    AMSIndexBaseRate_10007052: Annotated[
        float | None, Field(alias='AMSIndexBaseRate-10007052')
    ] = None
    AMSIndexRate_10007053: Annotated[
        float | None, Field(alias='AMSIndexRate-10007053')
    ] = None
    AMSAgreementLineType_10007054: Annotated[
        int | None, Field(alias='AMSAgreementLineType-10007054')
    ] = None
    AMSAgreementLineNo_10007055: Annotated[
        str | None, Field(alias='AMSAgreementLineNo-10007055')
    ] = None
    AMSAgreementLineLineNo_10007059: Annotated[
        int | None, Field(alias='AMSAgreementLineLineNo-10007059')
    ] = None
    AMSInvoicePrintingGroup_10007060: Annotated[
        str | None, Field(alias='AMSInvoicePrintingGroup-10007060')
    ] = None
    WJOBPrintOrder_10007200: Annotated[
        int | None, Field(alias='WJOBPrintOrder-10007200')
    ] = None
    WJOBCostResource_10007201: Annotated[
        bool | None, Field(alias='WJOBCostResource-10007201')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
