"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  SalesInvoiceHeader-112.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Salesinvoiceheader112(SparkModel):
    SelltoCustomerNo_2: Annotated[str | None, Field(alias='SelltoCustomerNo-2')] = None
    No_3: Annotated[str | None, Field(alias='No-3')] = None
    BilltoCustomerNo_4: Annotated[str | None, Field(alias='BilltoCustomerNo-4')] = None
    BilltoName_5: Annotated[str | None, Field(alias='BilltoName-5')] = None
    BilltoName2_6: Annotated[str | None, Field(alias='BilltoName2-6')] = None
    BilltoAddress_7: Annotated[str | None, Field(alias='BilltoAddress-7')] = None
    BilltoAddress2_8: Annotated[str | None, Field(alias='BilltoAddress2-8')] = None
    BilltoCity_9: Annotated[str | None, Field(alias='BilltoCity-9')] = None
    BilltoContact_10: Annotated[str | None, Field(alias='BilltoContact-10')] = None
    YourReference_11: Annotated[str | None, Field(alias='YourReference-11')] = None
    ShiptoCode_12: Annotated[str | None, Field(alias='ShiptoCode-12')] = None
    ShiptoName_13: Annotated[str | None, Field(alias='ShiptoName-13')] = None
    ShiptoName2_14: Annotated[str | None, Field(alias='ShiptoName2-14')] = None
    ShiptoAddress_15: Annotated[str | None, Field(alias='ShiptoAddress-15')] = None
    ShiptoAddress2_16: Annotated[str | None, Field(alias='ShiptoAddress2-16')] = None
    ShiptoCity_17: Annotated[str | None, Field(alias='ShiptoCity-17')] = None
    ShiptoContact_18: Annotated[str | None, Field(alias='ShiptoContact-18')] = None
    OrderDate_19: Annotated[str | None, Field(alias='OrderDate-19')] = None
    PostingDate_20: Annotated[str | None, Field(alias='PostingDate-20')] = None
    ShipmentDate_21: Annotated[str | None, Field(alias='ShipmentDate-21')] = None
    PostingDescription_22: Annotated[
        str | None, Field(alias='PostingDescription-22')
    ] = None
    PaymentTermsCode_23: Annotated[str | None, Field(alias='PaymentTermsCode-23')] = (
        None
    )
    DueDate_24: Annotated[str | None, Field(alias='DueDate-24')] = None
    PaymentDiscount_25: Annotated[float | None, Field(alias='PaymentDiscount-25')] = (
        None
    )
    PmtDiscountDate_26: Annotated[str | None, Field(alias='PmtDiscountDate-26')] = None
    ShipmentMethodCode_27: Annotated[
        str | None, Field(alias='ShipmentMethodCode-27')
    ] = None
    LocationCode_28: Annotated[str | None, Field(alias='LocationCode-28')] = None
    ShortcutDimension1Code_29: Annotated[
        str | None, Field(alias='ShortcutDimension1Code-29')
    ] = None
    ShortcutDimension2Code_30: Annotated[
        str | None, Field(alias='ShortcutDimension2Code-30')
    ] = None
    CustomerPostingGroup_31: Annotated[
        str | None, Field(alias='CustomerPostingGroup-31')
    ] = None
    CurrencyCode_32: Annotated[str | None, Field(alias='CurrencyCode-32')] = None
    CurrencyFactor_33: Annotated[float | None, Field(alias='CurrencyFactor-33')] = None
    CustomerPriceGroup_34: Annotated[
        str | None, Field(alias='CustomerPriceGroup-34')
    ] = None
    PricesIncludingVAT_35: Annotated[
        bool | None, Field(alias='PricesIncludingVAT-35')
    ] = None
    InvoiceDiscCode_37: Annotated[str | None, Field(alias='InvoiceDiscCode-37')] = None
    CustomerDiscGroup_40: Annotated[str | None, Field(alias='CustomerDiscGroup-40')] = (
        None
    )
    LanguageCode_41: Annotated[str | None, Field(alias='LanguageCode-41')] = None
    FormatRegion_42: Annotated[str | None, Field(alias='FormatRegion-42')] = None
    SalespersonCode_43: Annotated[str | None, Field(alias='SalespersonCode-43')] = None
    OrderNo_44: Annotated[str | None, Field(alias='OrderNo-44')] = None
    NoPrinted_47: Annotated[int | None, Field(alias='NoPrinted-47')] = None
    OnHold_51: Annotated[str | None, Field(alias='OnHold-51')] = None
    AppliestoDocType_52: Annotated[int | None, Field(alias='AppliestoDocType-52')] = (
        None
    )
    AppliestoDocNo_53: Annotated[str | None, Field(alias='AppliestoDocNo-53')] = None
    BalAccountNo_55: Annotated[str | None, Field(alias='BalAccountNo-55')] = None
    VATRegistrationNo_70: Annotated[str | None, Field(alias='VATRegistrationNo-70')] = (
        None
    )
    ReasonCode_73: Annotated[str | None, Field(alias='ReasonCode-73')] = None
    GenBusPostingGroup_74: Annotated[
        str | None, Field(alias='GenBusPostingGroup-74')
    ] = None
    EU3PartyTrade_75: Annotated[bool | None, Field(alias='EU3PartyTrade-75')] = None
    TransactionType_76: Annotated[str | None, Field(alias='TransactionType-76')] = None
    TransportMethod_77: Annotated[str | None, Field(alias='TransportMethod-77')] = None
    VATCountryRegionCode_78: Annotated[
        str | None, Field(alias='VATCountryRegionCode-78')
    ] = None
    SelltoCustomerName_79: Annotated[
        str | None, Field(alias='SelltoCustomerName-79')
    ] = None
    SelltoCustomerName2_80: Annotated[
        str | None, Field(alias='SelltoCustomerName2-80')
    ] = None
    SelltoAddress_81: Annotated[str | None, Field(alias='SelltoAddress-81')] = None
    SelltoAddress2_82: Annotated[str | None, Field(alias='SelltoAddress2-82')] = None
    SelltoCity_83: Annotated[str | None, Field(alias='SelltoCity-83')] = None
    SelltoContact_84: Annotated[str | None, Field(alias='SelltoContact-84')] = None
    BilltoPostCode_85: Annotated[str | None, Field(alias='BilltoPostCode-85')] = None
    BilltoCounty_86: Annotated[str | None, Field(alias='BilltoCounty-86')] = None
    BilltoCountryRegionCode_87: Annotated[
        str | None, Field(alias='BilltoCountryRegionCode-87')
    ] = None
    SelltoPostCode_88: Annotated[str | None, Field(alias='SelltoPostCode-88')] = None
    SelltoCounty_89: Annotated[str | None, Field(alias='SelltoCounty-89')] = None
    SelltoCountryRegionCode_90: Annotated[
        str | None, Field(alias='SelltoCountryRegionCode-90')
    ] = None
    ShiptoPostCode_91: Annotated[str | None, Field(alias='ShiptoPostCode-91')] = None
    ShiptoCounty_92: Annotated[str | None, Field(alias='ShiptoCounty-92')] = None
    ShiptoCountryRegionCode_93: Annotated[
        str | None, Field(alias='ShiptoCountryRegionCode-93')
    ] = None
    BalAccountType_94: Annotated[int | None, Field(alias='BalAccountType-94')] = None
    ExitPoint_97: Annotated[str | None, Field(alias='ExitPoint-97')] = None
    Correction_98: Annotated[bool | None, Field(alias='Correction-98')] = None
    DocumentDate_99: Annotated[str | None, Field(alias='DocumentDate-99')] = None
    ExternalDocumentNo_100: Annotated[
        str | None, Field(alias='ExternalDocumentNo-100')
    ] = None
    Area_101: Annotated[str | None, Field(alias='Area-101')] = None
    TransactionSpecification_102: Annotated[
        str | None, Field(alias='TransactionSpecification-102')
    ] = None
    PaymentMethodCode_104: Annotated[
        str | None, Field(alias='PaymentMethodCode-104')
    ] = None
    ShippingAgentCode_105: Annotated[
        str | None, Field(alias='ShippingAgentCode-105')
    ] = None
    PackageTrackingNo_106: Annotated[
        str | None, Field(alias='PackageTrackingNo-106')
    ] = None
    PreAssignedNoSeries_107: Annotated[
        str | None, Field(alias='PreAssignedNoSeries-107')
    ] = None
    NoSeries_108: Annotated[str | None, Field(alias='NoSeries-108')] = None
    OrderNoSeries_110: Annotated[str | None, Field(alias='OrderNoSeries-110')] = None
    PreAssignedNo_111: Annotated[str | None, Field(alias='PreAssignedNo-111')] = None
    UserID_112: Annotated[str | None, Field(alias='UserID-112')] = None
    SourceCode_113: Annotated[str | None, Field(alias='SourceCode-113')] = None
    TaxAreaCode_114: Annotated[str | None, Field(alias='TaxAreaCode-114')] = None
    TaxLiable_115: Annotated[bool | None, Field(alias='TaxLiable-115')] = None
    VATBusPostingGroup_116: Annotated[
        str | None, Field(alias='VATBusPostingGroup-116')
    ] = None
    VATBaseDiscount_119: Annotated[float | None, Field(alias='VATBaseDiscount-119')] = (
        None
    )
    InvoiceDiscountCalculation_121: Annotated[
        int | None, Field(alias='InvoiceDiscountCalculation-121')
    ] = None
    InvoiceDiscountValue_122: Annotated[
        float | None, Field(alias='InvoiceDiscountValue-122')
    ] = None
    PrepaymentNoSeries_131: Annotated[
        str | None, Field(alias='PrepaymentNoSeries-131')
    ] = None
    PrepaymentInvoice_136: Annotated[
        bool | None, Field(alias='PrepaymentInvoice-136')
    ] = None
    PrepaymentOrderNo_137: Annotated[
        str | None, Field(alias='PrepaymentOrderNo-137')
    ] = None
    QuoteNo_151: Annotated[str | None, Field(alias='QuoteNo-151')] = None
    CompanyBankAccountCode_163: Annotated[
        str | None, Field(alias='CompanyBankAccountCode-163')
    ] = None
    SelltoPhoneNo_171: Annotated[str | None, Field(alias='SelltoPhoneNo-171')] = None
    SelltoEMail_172: Annotated[str | None, Field(alias='SelltoEMail-172')] = None
    VATReportingDate_179: Annotated[str | None, Field(alias='VATReportingDate-179')] = (
        None
    )
    PaymentReference_180: Annotated[str | None, Field(alias='PaymentReference-180')] = (
        None
    )
    DimensionSetID_480: Annotated[int | None, Field(alias='DimensionSetID-480')] = None
    PaymentServiceSetID_600: Annotated[
        int | None, Field(alias='PaymentServiceSetID-600')
    ] = None
    DocumentExchangeIdentifier_710: Annotated[
        str | None, Field(alias='DocumentExchangeIdentifier-710')
    ] = None
    DocumentExchangeStatus_711: Annotated[
        int | None, Field(alias='DocumentExchangeStatus-711')
    ] = None
    DocExchOriginalIdentifier_712: Annotated[
        str | None, Field(alias='DocExchOriginalIdentifier-712')
    ] = None
    CoupledtoCRM_720: Annotated[bool | None, Field(alias='CoupledtoCRM-720')] = None
    DirectDebitMandateID_1200: Annotated[
        str | None, Field(alias='DirectDebitMandateID-1200')
    ] = None
    CustLedgerEntryNo_1304: Annotated[
        int | None, Field(alias='CustLedgerEntryNo-1304')
    ] = None
    CampaignNo_5050: Annotated[str | None, Field(alias='CampaignNo-5050')] = None
    SelltoContactNo_5052: Annotated[str | None, Field(alias='SelltoContactNo-5052')] = (
        None
    )
    BilltoContactNo_5053: Annotated[str | None, Field(alias='BilltoContactNo-5053')] = (
        None
    )
    OpportunityNo_5055: Annotated[str | None, Field(alias='OpportunityNo-5055')] = None
    ResponsibilityCenter_5700: Annotated[
        str | None, Field(alias='ResponsibilityCenter-5700')
    ] = None
    PriceCalculationMethod_7000: Annotated[
        int | None, Field(alias='PriceCalculationMethod-7000')
    ] = None
    AllowLineDisc_7001: Annotated[bool | None, Field(alias='AllowLineDisc-7001')] = None
    GetShipmentUsed_7200: Annotated[
        bool | None, Field(alias='GetShipmentUsed-7200')
    ] = None
    DraftInvoiceSystemId_8001: Annotated[
        UUID | None, Field(alias='DraftInvoiceSystemId-8001')
    ] = None
    ShpfyOrderId_30100: Annotated[int | None, Field(alias='ShpfyOrderId-30100')] = None
    ShpfyOrderNo_30101: Annotated[str | None, Field(alias='ShpfyOrderNo-30101')] = None
    PTENmerverkbeini_65100: Annotated[
        str | None, Field(alias='PTENmerverkbeini-65100')
    ] = None
    PTEDocumentSendingProfile_65101: Annotated[
        str | None, Field(alias='PTEDocumentSendingProfile-65101')
    ] = None
    PTEOCRband_65102: Annotated[str | None, Field(alias='PTEOCRband-65102')] = None
    PTEBankAccountCode_65103: Annotated[
        str | None, Field(alias='PTEBankAccountCode-65103')
    ] = None
    PTEUseSaleslines_65104: Annotated[
        bool | None, Field(alias='PTEUseSaleslines-65104')
    ] = None
    AMSAgreementNo_10007050: Annotated[
        str | None, Field(alias='AMSAgreementNo-10007050')
    ] = None
    AMSNextPeriodDate_10007052: Annotated[
        str | None, Field(alias='AMSNextPeriodDate-10007052')
    ] = None
    AMSPeriod_10007053: Annotated[str | None, Field(alias='AMSPeriod-10007053')] = None
    AMSAgreementType_10007055: Annotated[
        str | None, Field(alias='AMSAgreementType-10007055')
    ] = None
    AMSAgreementPeriodGroup_10007056: Annotated[
        str | None, Field(alias='AMSAgreementPeriodGroup-10007056')
    ] = None
    AMSPeriodEntryNo_10007059: Annotated[
        int | None, Field(alias='AMSPeriodEntryNo-10007059')
    ] = None
    AMSPeriodInvoicingType_10007065: Annotated[
        int | None, Field(alias='AMSPeriodInvoicingType-10007065')
    ] = None
    AMSNotOverageRelated_10007066: Annotated[
        bool | None, Field(alias='AMSNotOverageRelated-10007066')
    ] = None
    AMSBillingRunBatchNo_10007067: Annotated[
        int | None, Field(alias='AMSBillingRunBatchNo-10007067')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
