"""
Auto-generated models from schema.
DO NOT EDIT MANUALLY - regenerate using regenerate_models.py
"""

# generated by datamodel-codegen:
#   filename:  Vendor-23.cdm.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel


class Vendor23(SparkModel):
    No_1: Annotated[str | None, Field(alias='No-1')] = None
    Name_2: Annotated[str | None, Field(alias='Name-2')] = None
    SearchName_3: Annotated[str | None, Field(alias='SearchName-3')] = None
    Name2_4: Annotated[str | None, Field(alias='Name2-4')] = None
    Address_5: Annotated[str | None, Field(alias='Address-5')] = None
    Address2_6: Annotated[str | None, Field(alias='Address2-6')] = None
    City_7: Annotated[str | None, Field(alias='City-7')] = None
    Contact_8: Annotated[str | None, Field(alias='Contact-8')] = None
    PhoneNo_9: Annotated[str | None, Field(alias='PhoneNo-9')] = None
    TelexNo_10: Annotated[str | None, Field(alias='TelexNo-10')] = None
    OurAccountNo_14: Annotated[str | None, Field(alias='OurAccountNo-14')] = None
    TerritoryCode_15: Annotated[str | None, Field(alias='TerritoryCode-15')] = None
    GlobalDimension1Code_16: Annotated[
        str | None, Field(alias='GlobalDimension1Code-16')
    ] = None
    GlobalDimension2Code_17: Annotated[
        str | None, Field(alias='GlobalDimension2Code-17')
    ] = None
    BudgetedAmount_19: Annotated[float | None, Field(alias='BudgetedAmount-19')] = None
    VendorPostingGroup_21: Annotated[
        str | None, Field(alias='VendorPostingGroup-21')
    ] = None
    CurrencyCode_22: Annotated[str | None, Field(alias='CurrencyCode-22')] = None
    LanguageCode_24: Annotated[str | None, Field(alias='LanguageCode-24')] = None
    RegistrationNumber_25: Annotated[
        str | None, Field(alias='RegistrationNumber-25')
    ] = None
    StatisticsGroup_26: Annotated[int | None, Field(alias='StatisticsGroup-26')] = None
    PaymentTermsCode_27: Annotated[str | None, Field(alias='PaymentTermsCode-27')] = (
        None
    )
    FinChargeTermsCode_28: Annotated[
        str | None, Field(alias='FinChargeTermsCode-28')
    ] = None
    PurchaserCode_29: Annotated[str | None, Field(alias='PurchaserCode-29')] = None
    ShipmentMethodCode_30: Annotated[
        str | None, Field(alias='ShipmentMethodCode-30')
    ] = None
    ShippingAgentCode_31: Annotated[str | None, Field(alias='ShippingAgentCode-31')] = (
        None
    )
    InvoiceDiscCode_33: Annotated[str | None, Field(alias='InvoiceDiscCode-33')] = None
    CountryRegionCode_35: Annotated[str | None, Field(alias='CountryRegionCode-35')] = (
        None
    )
    Blocked_39: Annotated[int | None, Field(alias='Blocked-39')] = None
    PaytoVendorNo_45: Annotated[str | None, Field(alias='PaytoVendorNo-45')] = None
    Priority_46: Annotated[int | None, Field(alias='Priority-46')] = None
    PaymentMethodCode_47: Annotated[str | None, Field(alias='PaymentMethodCode-47')] = (
        None
    )
    FormatRegion_48: Annotated[str | None, Field(alias='FormatRegion-48')] = None
    LastModifiedDateTime_53: Annotated[
        datetime | None, Field(alias='LastModifiedDateTime-53')
    ] = None
    LastDateModified_54: Annotated[str | None, Field(alias='LastDateModified-54')] = (
        None
    )
    ApplicationMethod_80: Annotated[int | None, Field(alias='ApplicationMethod-80')] = (
        None
    )
    PricesIncludingVAT_82: Annotated[
        bool | None, Field(alias='PricesIncludingVAT-82')
    ] = None
    FaxNo_84: Annotated[str | None, Field(alias='FaxNo-84')] = None
    TelexAnswerBack_85: Annotated[str | None, Field(alias='TelexAnswerBack-85')] = None
    VATRegistrationNo_86: Annotated[str | None, Field(alias='VATRegistrationNo-86')] = (
        None
    )
    GenBusPostingGroup_88: Annotated[
        str | None, Field(alias='GenBusPostingGroup-88')
    ] = None
    GLN_90: Annotated[str | None, Field(alias='GLN-90')] = None
    PostCode_91: Annotated[str | None, Field(alias='PostCode-91')] = None
    County_92: Annotated[str | None, Field(alias='County-92')] = None
    EORINumber_93: Annotated[str | None, Field(alias='EORINumber-93')] = None
    EMail_102: Annotated[str | None, Field(alias='EMail-102')] = None
    HomePage_103: Annotated[str | None, Field(alias='HomePage-103')] = None
    NoSeries_107: Annotated[str | None, Field(alias='NoSeries-107')] = None
    TaxAreaCode_108: Annotated[str | None, Field(alias='TaxAreaCode-108')] = None
    TaxLiable_109: Annotated[bool | None, Field(alias='TaxLiable-109')] = None
    VATBusPostingGroup_110: Annotated[
        str | None, Field(alias='VATBusPostingGroup-110')
    ] = None
    BlockPaymentTolerance_116: Annotated[
        bool | None, Field(alias='BlockPaymentTolerance-116')
    ] = None
    ICPartnerCode_119: Annotated[str | None, Field(alias='ICPartnerCode-119')] = None
    Prepayment_124: Annotated[float | None, Field(alias='Prepayment-124')] = None
    PartnerType_132: Annotated[int | None, Field(alias='PartnerType-132')] = None
    IntrastatPartnerType_133: Annotated[
        int | None, Field(alias='IntrastatPartnerType-133')
    ] = None
    ExcludefromPmtPractices_134: Annotated[
        bool | None, Field(alias='ExcludefromPmtPractices-134')
    ] = None
    CompanySizeCode_135: Annotated[str | None, Field(alias='CompanySizeCode-135')] = (
        None
    )
    PrivacyBlocked_150: Annotated[bool | None, Field(alias='PrivacyBlocked-150')] = None
    DisableSearchbyName_160: Annotated[
        bool | None, Field(alias='DisableSearchbyName-160')
    ] = None
    CreditorNo_170: Annotated[str | None, Field(alias='CreditorNo-170')] = None
    AllowMultiplePostingGroups_175: Annotated[
        bool | None, Field(alias='AllowMultiplePostingGroups-175')
    ] = None
    PreferredBankAccountCode_288: Annotated[
        str | None, Field(alias='PreferredBankAccountCode-288')
    ] = None
    CoupledtoCRM_720: Annotated[bool | None, Field(alias='CoupledtoCRM-720')] = None
    CashFlowPaymentTermsCode_840: Annotated[
        str | None, Field(alias='CashFlowPaymentTermsCode-840')
    ] = None
    PrimaryContactNo_5049: Annotated[
        str | None, Field(alias='PrimaryContactNo-5049')
    ] = None
    MobilePhoneNo_5061: Annotated[str | None, Field(alias='MobilePhoneNo-5061')] = None
    ResponsibilityCenter_5700: Annotated[
        str | None, Field(alias='ResponsibilityCenter-5700')
    ] = None
    LocationCode_5701: Annotated[str | None, Field(alias='LocationCode-5701')] = None
    LeadTimeCalculation_5790: Annotated[
        str | None, Field(alias='LeadTimeCalculation-5790')
    ] = None
    PriceCalculationMethod_7000: Annotated[
        int | None, Field(alias='PriceCalculationMethod-7000')
    ] = None
    BaseCalendarCode_7600: Annotated[
        str | None, Field(alias='BaseCalendarCode-7600')
    ] = None
    DocumentSendingProfile_7601: Annotated[
        str | None, Field(alias='DocumentSendingProfile-7601')
    ] = None
    ValidateEUVatRegNo_7602: Annotated[
        bool | None, Field(alias='ValidateEUVatRegNo-7602')
    ] = None
    CurrencyId_8001: Annotated[UUID | None, Field(alias='CurrencyId-8001')] = None
    PaymentTermsId_8002: Annotated[UUID | None, Field(alias='PaymentTermsId-8002')] = (
        None
    )
    PaymentMethodId_8003: Annotated[
        UUID | None, Field(alias='PaymentMethodId-8003')
    ] = None
    OverReceiptCode_8510: Annotated[str | None, Field(alias='OverReceiptCode-8510')] = (
        None
    )
    PTEMicrosoftafslttur_65000: Annotated[
        float | None, Field(alias='PTEMicrosoftafslttur-65000')
    ] = None
    PTEGjaldkeri_65001: Annotated[str | None, Field(alias='PTEGjaldkeri-65001')] = None
    PTESmigjaldkera_65002: Annotated[
        str | None, Field(alias='PTESmigjaldkera-65002')
    ] = None
    PTEHeitikeju_65003: Annotated[str | None, Field(alias='PTEHeitikeju-65003')] = None
    PTEAfmrkuntgjaldaflokks_65004: Annotated[
        str | None, Field(alias='PTEAfmrkuntgjaldaflokks-65004')
    ] = None
    PTEEkkiuppskrifa_65005: Annotated[
        bool | None, Field(alias='PTEEkkiuppskrifa-65005')
    ] = None
    PTEPrentalaunamia_65006: Annotated[
        bool | None, Field(alias='PTEPrentalaunamia-65006')
    ] = None
    PTEjafnaargreislur_65007: Annotated[
        float | None, Field(alias='PTEjafnaargreislur-65007')
    ] = None
    PTEEkkigreislutillgu_65008: Annotated[
        bool | None, Field(alias='PTEEkkigreislutillgu-65008')
    ] = None
    PTEContractor_65009: Annotated[bool | None, Field(alias='PTEContractor-65009')] = (
        None
    )
    PTESleppagreislutillgu_65010: Annotated[
        bool | None, Field(alias='PTESleppagreislutillgu-65010')
    ] = None
    CTRContractor_10027575: Annotated[
        bool | None, Field(alias='CTRContractor-10027575')
    ] = None
    timestamp_0: Annotated[int | None, Field(alias='timestamp-0')] = None
    systemId_2000000000: Annotated[UUID | None, Field(alias='systemId-2000000000')] = (
        None
    )
    SystemCreatedAt_2000000001: Annotated[
        datetime | None, Field(alias='SystemCreatedAt-2000000001')
    ] = None
    SystemCreatedBy_2000000002: Annotated[
        UUID | None, Field(alias='SystemCreatedBy-2000000002')
    ] = None
    SystemModifiedAt_2000000003: Annotated[
        datetime | None, Field(alias='SystemModifiedAt-2000000003')
    ] = None
    SystemModifiedBy_2000000004: Annotated[
        UUID | None, Field(alias='SystemModifiedBy-2000000004')
    ] = None
    field_Company: Annotated[str | None, Field(alias='$Company')] = None
