[tool.poetry]
name = "fabric-api"
version = "0.1.0"
description = "ConnectWise PSA to Microsoft Fabric OneLake integration."
authors = ["Hákon Freyr Gunnarsson <hakonf@wise.is>"]
readme = "README.md"
packages = [{ include = "fabric_api" }]

[tool.poetry.dependencies]
python = ">=3.11"
requests = "*"
pandas = ">=1.5.0"
pyarrow = ">=10.0.0"
python-dotenv = "*"

[tool.poetry.extras]
fabric = ["pyspark"]
azure = ["azure-identity", "azure-keyvault-secrets"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I", "N"]
exclude = [".venv", "venv", "build", "dist"]
# Optionally, add more rules or ignore patterns here

[tool.basedpyright]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
exclude = [".venv", "venv", "build", "dist"]
# Explicitly set python version and executable
pythonVersion = "3.11"
pythonPlatform = "Windows"
pythonPath = "C:/Python311/python.exe"

[tool.uv]
# uv-specific settings can be added here
