[tool.poetry]
name = "fabric-api"
version = "0.2.0"
description = "ConnectWise PSA to Microsoft Fabric OneLake integration."
authors = ["Hákon Freyr Gunnarsson <hakonf@wise.is>"]
readme = "README.md"
packages = [{ include = "fabric_api" }]

[tool.poetry.dependencies]
python = ">=3.10"
requests = "*"
pandas = ">=1.5.0"
pyarrow = ">=10.0.0"
python-dotenv = "*"
pydantic = ">=2.11.4"
pyspark = "*"
pyright = "*"
[tool.poetry.extras]
fabric = ["pyspark"]
azure = ["azure-identity", "azure-keyvault-secrets"]
sparkdantic = ["sparkdantic"]
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
exclude = [".venv", "venv", "build", "dist"]
# Optionally, add more rules or ignore patterns here

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N"]

[tool.windsurfPyright]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
languageServer = "windsurfPyright"
exclude = [".venv", "venv", "build", "dist"]

[tool.uv]
# uv-specific settings can be added here
