# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel


class CampaignSubType(SparkModel):
    id: int | None
    typeId: int | None
    name: str | None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')]
