# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel

from .. import CampaignTypeReference


class CampaignSubType(SparkModel):
    id: int | None = None
    type: CampaignTypeReference | None = None
    name: Annotated[str | None, Field(description=' Max length: 100;')] = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None
