# ConnectWise Gold Layer Dimension Table Schemas
# Clean, normalized schemas without the current clusterfuck

dimensions:
  # Core Business Dimensions
  dimcompany:
    table_name: "gold.dimcompany"
    primary_key: "CompanyKey"
    natural_key: "companyId"
    source_table: "silver.silver_cw_timeentry" # Most complete company data
    columns:
      - name: "CompanyKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "companyId"
        type: "integer"
        description: "Natural key from ConnectWise"
      - name: "companyName"
        type: "string"
        description: "Company display name"
      - name: "companyType"
        type: "string"
        description: "Company classification"

  dimmember:
    table_name: "gold.dimmember"
    primary_key: "MemberKey"
    natural_key: "memberId"
    source_table: "silver.silver_cw_member"
    columns:
      - name: "MemberKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "memberId"
        type: "integer"
        description: "Natural key from ConnectWise"
      - name: "memberName"
        type: "string"
        description: "Full display name"
      - name: "officeEmail"
        type: "string"
      - name: "inactiveFlag"
        type: "boolean"
        description: "Is member inactive"

  dimagreementtype:
    table_name: "gold.dimagreementtype"
    primary_key: "AgreementTypeKey"
    natural_key: "agreementType"
    source_table: "silver.silver_cw_agreement"
    columns:
      - name: "AgreementTypeKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "typeName"
        type: "string"
        description: "Agreement type name (natural key)"
      - name: "agreementCategory"
        type: "string"
        description: "Simplified category (Timapottur, Internal, Operations, Software, Service, Other)"

  # Status/Classification Dimensions
  dimbillablestatus:
    table_name: "gold.dimbillablestatus"
    primary_key: "BillableStatusKey"
    natural_key: "billableOption"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "BillableStatusKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "billableOption"
        type: "string"
        description: "Billable status (Billable, DoNotBill, NoCharge)"
      - name: "billableCategory"
        type: "string"
        description: "Simplified category (Billable, NonBillable)"

  dimtimeentrystatus:
    table_name: "gold.dimtimeentrystatus"
    primary_key: "TimeEntryStatusKey"
    natural_key: "status"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "TimeEntryStatusKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "status"
        type: "string"
        description: "Time entry status"
      - name: "statusCategory"
        type: "string"
        description: "Grouped status (Open, Pending, Approved, Ready, Billed, Closed)"

  dimchargetype:
    table_name: "gold.dimchargetype"
    primary_key: "ChargeTypeKey"
    natural_key: "chargeToType"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "ChargeTypeKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "chargeToType"
        type: "string"
        description: "What work is charged to (Company, ServiceTicket, ProjectTicket, etc.)"
      - name: "chargeCategory"
        type: "string"
        description: "Simplified category (Company, Ticket, Project)"

  # Work Classification Dimensions
  dimworktype:
    table_name: "gold.dimworktype"
    primary_key: "WorkTypeKey"
    natural_key: "workTypeId"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "WorkTypeKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "workTypeId"
        type: "integer"
        description: "Work type ID from ConnectWise"
      - name: "workTypeName"
        type: "string"
        description: "Work type display name"

  dimworkrole:
    table_name: "gold.dimworkrole"
    primary_key: "WorkRoleKey"
    natural_key: "workRoleId"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "WorkRoleKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "workRoleId"
        type: "integer"
        description: "Work role ID from ConnectWise"
      - name: "workRoleName"
        type: "string"
        description: "Work role display name"

  # Organizational Dimensions
  dimdepartment:
    table_name: "gold.dimdepartment"
    primary_key: "DepartmentKey"
    natural_key: "departmentId"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "DepartmentKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "departmentId"
        type: "integer"
        description: "Department ID from ConnectWise"
      - name: "departmentName"
        type: "string"
        description: "Department display name"

  dimbusinessunit:
    table_name: "gold.dimbusinessunit"
    primary_key: "BusinessUnitKey"
    natural_key: "businessUnitId"
    source_table: "silver.silver_cw_timeentry"
    columns:
      - name: "BusinessUnitKey"
        type: "bigint"
        description: "Surrogate key"
      - name: "businessUnitId"
        type: "integer"
        description: "Business unit ID from ConnectWise"
      - name: "businessGroupDesc"
        type: "string"
        description: "Business unit description"
