# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json
#   timestamp: 2025-05-27T16:44:24+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import Field
from sparkdantic import SparkModel

from . import CustomFieldValue


class Adjustment(SparkModel):
    id: int | None = None
    amount: float | None = None
    description: str | None = None
    """
     Max length: 1000;
    """
    effectiveDate: datetime | None = None
    agreementId: int | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')
    customFields: list[CustomFieldValue] | None = None
