# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json
#   timestamp: 2025-05-27T16:26:22+00:00

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel

from . import (
    CompanyReference,
    CompanyTypeReference,
    ConfigurationQuestion,
    ConfigurationStatusReference,
    ConfigurationTypeReference,
    ContactReference,
    ContactTypeReference,
    CustomFieldValue,
    ManufacturerReference,
    MemberReference,
    SiteReference,
    SLAReference,
    SystemDepartmentReference,
    SystemLocationReference,
)


class CompanyTypeAssociation(SparkModel):
    id: int | None = None
    type: CompanyTypeReference
    company: CompanyReference
    field_info: dict[str, str] | None = Field(None, alias='_info')


class Configuration(SparkModel):
    id: int | None = None
    name: str
    """
     Max length: 100;
    """
    type: ConfigurationTypeReference
    status: ConfigurationStatusReference | None = None
    company: CompanyReference
    contact: ContactReference | None = None
    site: SiteReference | None = None
    locationId: int | None = None
    location: SystemLocationReference | None = None
    businessUnitId: int | None = None
    department: SystemDepartmentReference | None = None
    deviceIdentifier: str | None = None
    """
     Max length: 100;
    """
    serialNumber: str | None = None
    """
     Max length: 250;
    """
    modelNumber: str | None = None
    """
     Max length: 50;
    """
    tagNumber: str | None = None
    """
     Max length: 50;
    """
    purchaseDate: datetime | None = None
    installationDate: datetime | None = None
    installedBy: MemberReference | None = None
    warrantyExpirationDate: datetime | None = None
    vendorNotes: str | None = None
    notes: str | None = None
    macAddress: str | None = None
    """
     Max length: 25;
    """
    lastLoginName: str | None = None
    """
     Max length: 100;
    """
    billFlag: bool | None = None
    backupSuccesses: int | None = None
    backupIncomplete: int | None = None
    backupFailed: int | None = None
    backupRestores: int | None = None
    lastBackupDate: datetime | None = None
    backupServerName: str | None = None
    """
     Max length: 50;
    """
    backupBillableSpaceGb: float | None = None
    backupProtectedDeviceList: str | None = None
    backupYear: int | None = None
    backupMonth: int | None = None
    ipAddress: str | None = None
    """
     Max length: 50;
    """
    defaultGateway: str | None = None
    """
     Max length: 50;
    """
    osType: str | None = None
    """
     Max length: 250;
    """
    osInfo: str | None = None
    """
     Max length: 250;
    """
    cpuSpeed: str | None = None
    """
     Max length: 100;
    """
    ram: str | None = None
    """
     Max length: 25;
    """
    localHardDrives: str | None = None
    parentConfigurationId: int | None = None
    vendor: CompanyReference | None = None
    manufacturer: ManufacturerReference | None = None
    questions: list[ConfigurationQuestion] | None = None
    activeFlag: bool | None = None
    managementLink: str | None = None
    """
     Max length: 1000;
    """
    remoteLink: str | None = None
    """
     Max length: 1000;
    """
    sla: SLAReference | None = None
    mobileGuid: UUID | None = None
    displayVendorFlag: bool | None = None
    companyLocationId: int | None = None
    showRemoteFlag: bool | None = None
    showAutomateFlag: bool | None = None
    needsRenewalFlag: bool | None = None
    manufacturerPartNumber: str | None = None
    """
     Max length: 50;
    """
    field_info: dict[str, str] | None = Field(None, alias='_info')
    customFields: list[CustomFieldValue] | None = None


class ContactTypeAssociation(SparkModel):
    id: int | None = None
    type: ContactTypeReference
    contact: ContactReference
    field_info: dict[str, str] | None = Field(None, alias='_info')
