# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json
#   timestamp: 2025-05-27T16:44:24+00:00

from __future__ import annotations

from pydantic import Field
from sparkdantic import SparkModel

from . import ContactReference, ContactTypeReference


class ContactTypeAssociation(SparkModel):
    id: int | None = None
    type: ContactTypeReference
    contact: ContactReference
    field_info: dict[str, str] | None = Field(None, alias='_info')
