# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json
#   timestamp: 2025-05-27T16:44:24+00:00

from __future__ import annotations

from pydantic import Field
from sparkdantic import SparkModel

from . import CurrencyCodeReference


class Currency(SparkModel):
    id: int | None = None
    currencyIdentifier: str
    """
     Max length: 10;
    """
    name: str
    """
     Max length: 50;
    """
    symbol: str | None = None
    """
     Max length: 10;
    """
    displayIdFlag: bool | None = None
    displaySymbolFlag: bool | None = None
    currencyCode: CurrencyCodeReference | None = None
    thousandsSeparator: str | None = None
    """
     Max length: 1;
    """
    decimalSeparator: str | None = None
    """
     Max length: 1;
    """
    negativeParenthesesFlag: bool | None = None
    rightAlign: bool | None = None
    numberOfDecimals: int | None = None
    reportFormat: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')
