"""
PSA API models generated from OpenAPI schema by datamodel-code-generator.

Compatible with Pydantic v2 and SparkDantic for Spark schema generation.
This file contains all models to avoid circular imports and manage dependencies.
This file is autogenerated. Do not edit manually.
Generated by unified_etl/generators/generate_psa_models.py
"""
# flake8: noqa
# fmt: off

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel

# generated by datamodel-codegen:
#   filename:  tmpqn18gtzu.json


class AgreementReference(SparkModel):
    id: int | None = None
    name: str | None = None
    type: str | None = None
    chargeFirmFlag: bool | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


class ProjectReference(SparkModel):
    id: int | None = None
    name: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


class MemberReference(SparkModel):
    id: int | None = None
    identifier: str | None = None
    name: str | None = None
    dailyCapacity: float | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


OwnerLevelReference = ProjectReference


TaxCodeReference = ProjectReference


SLAReference = ProjectReference


SiteReference = ProjectReference


class BillingStatusReference(SparkModel):
    id: int | None = None
    name: str | None = None
    isClosed: bool | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


BatchReference = ProjectReference


ContactReference = ProjectReference


BillingSetupReference = ProjectReference


OpportunityReference = ProjectReference


class SystemDepartmentReference(SparkModel):
    id: int | None = None
    identifier: str | None = None
    name: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


CompanyReference = SystemDepartmentReference


class SalesOrderReference(SparkModel):
    id: int | None = None
    identifier: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


BillingCycleReference = ProjectReference


class WorkTypeReference(SparkModel):
    id: int | None = None
    name: str | None = None
    utilizationFlag: bool | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


AgreementTypeReference = ProjectReference


class InvoiceReference(SparkModel):
    id: int | None = None
    identifier: str | None = None
    billingType: str | None = None
    applyToType: str | None = None
    invoiceDate: str | None = None
    chargeFirmFlag: bool | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


ActivityReference = ProjectReference


class CustomFieldValue(SparkModel):
    id: int | None = None
    caption: str | None = None
    type: (
        Literal[
            'TextArea',
            'Button',
            'Currency',
            'Date',
            'Hyperlink',
            'IPAddress',
            'Checkbox',
            'Number',
            'Percent',
            'PhoneNumber',
            'Text',
            'Password',
        ]
        | None
    ) = None
    entryMethod: Literal['Date', 'EntryField', 'List', 'Option'] | None = None
    numberOfDecimals: int | None = None
    value: dict[str, Any] | None = None
    connectWiseId: str | None = None


class InvoiceTemplateReference(SparkModel):
    id: int | None = None
    """
    Gets or sets invoice Template Setup Id.
    """
    name: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


SystemLocationReference = ProjectReference


ProjectPhaseReference = ProjectReference


BillingUnitReference = ProjectReference


TimeSheetReference = ProjectReference


WorkRoleReference = ProjectReference


class TicketReference(SparkModel):
    id: int | None = None
    summary: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


BillingTermsReference = ProjectReference


ProjectTypeReference = ProjectReference


class CurrencyReference(SparkModel):
    id: int | None = None
    symbol: str | None = None
    currencyCode: str | None = None
    decimalSeparator: str | None = None
    numberOfDecimals: int | None = None
    thousandsSeparator: str | None = None
    negativeParenthesesFlag: bool | None = None
    displaySymbolFlag: bool | None = None
    currencyIdentifier: str | None = None
    displayIdFlag: bool | None = None
    rightAlign: bool | None = None
    name: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')


InvoiceTemplateDetailReference = ProjectReference


class TimeEntry(SparkModel):
    id: int | None = None
    company: CompanyReference | None = None
    companyType: str | None = None
    chargeToId: int | None = None
    """
    If chargeToId is not specified, we asume you enter time against the company specified
    """
    chargeToType: (
        Literal['Company', 'ServiceTicket', 'ProjectTicket', 'ChargeCode', 'Activity']
        | None
    ) = None
    """
    If chargeToId is not specified, we asume you enter time against the company specified
    """
    member: MemberReference | None = None
    locationId: int | None = None
    businessUnitId: int | None = None
    businessGroupDesc: str | None = None
    location: OwnerLevelReference | None = None
    department: BillingUnitReference | None = None
    workType: WorkTypeReference | None = None
    workRole: WorkRoleReference | None = None
    agreement: AgreementReference | None = None
    agreementType: str | None = None
    activity: ActivityReference | None = None
    opportunityRecid: int | None = None
    projectActivity: str | None = None
    territory: str | None = None
    timeStart: datetime
    timeEnd: datetime | None = None
    hoursDeduct: float | None = None
    actualHours: float | None = None
    billableOption: Literal['Billable', 'DoNotBill', 'NoCharge', 'NoDefault'] | None = (
        None
    )
    """
     Required On Updates;
    """
    notes: str | None = None
    internalNotes: str | None = None
    addToDetailDescriptionFlag: bool | None = None
    addToInternalAnalysisFlag: bool | None = None
    addToResolutionFlag: bool | None = None
    emailResourceFlag: bool | None = None
    """
    This is an action flag. To update this value use the /service/tickets endpoint automaticEmailResourceFlag field
    """
    emailContactFlag: bool | None = None
    """
    This is an action flag. To update this value use the /service/tickets endpoint automaticEmailContactFlag field
    """
    emailCcFlag: bool | None = None
    """
    This is an action flag. To update this value use the /service/tickets endpoint automaticEmailCcFlag field
    """
    emailCc: str | None = None
    """
    To update this value use the /service/tickets endpoint automaticEmailCc field
    """
    hoursBilled: float | None = None
    invoiceHours: float | None = None
    hourlyCost: str | None = None
    enteredBy: str | None = None
    dateEntered: datetime | None = None
    invoice: InvoiceReference | None = None
    mobileGuid: UUID | None = None
    hourlyRate: float | None = None
    """
    This field may only be Updated, it is defaulted on Create
    """
    overageRate: float | None = None
    agreementHours: float | None = None
    agreementAmount: float | None = None
    agreementAdjustment: float | None = None
    adjustment: float | None = None
    invoiceReady: int | None = None
    timeSheet: TimeSheetReference | None = None
    status: (
        Literal[
            'Open',
            'Rejected',
            'PendingApproval',
            'ErrorsCorrected',
            'PendingProjectApproval',
            'ApprovedByTierOne',
            'RejectBySecondTier',
            'ApprovedByTierTwo',
            'ReadyToBill',
            'Billed',
            'WrittenOff',
            'BilledAgreement',
        ]
        | None
    ) = None
    ticket: TicketReference | None = None
    project: ProjectReference | None = None
    phase: ProjectPhaseReference | None = None
    ticketBoard: str | None = None
    ticketStatus: str | None = None
    ticketType: str | None = None
    ticketSubType: str | None = None
    invoiceFlag: bool | None = None
    extendedInvoiceAmount: float | None = None
    locationName: str | None = None
    taxCode: TaxCodeReference | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')
    customFields: list[CustomFieldValue] | None = None


class Agreement(SparkModel):
    id: int | None = None
    name: str
    """
     Max length: 100;
    """
    type: AgreementTypeReference
    company: CompanyReference
    contact: ContactReference
    site: SiteReference | None = None
    subContractCompany: CompanyReference | None = None
    subContractContact: ContactReference | None = None
    parentAgreement: AgreementReference | None = None
    customerPO: str | None = None
    """
     Max length: 50;
    """
    location: SystemLocationReference | None = None
    department: SystemDepartmentReference | None = None
    restrictLocationFlag: bool | None = None
    restrictDepartmentFlag: bool | None = None
    startDate: datetime | None = None
    endDate: datetime | None = None
    noEndingDateFlag: bool | None = None
    opportunity: OpportunityReference | None = None
    cancelledFlag: bool | None = None
    dateCancelled: datetime | None = None
    reasonCancelled: str | None = None
    """
     Max length: 100;
    """
    sla: SLAReference | None = None
    workOrder: str | None = None
    """
     Max length: 20;
    """
    internalNotes: str | None = None
    applicationUnits: Literal['Amount', 'Hours', 'Incidents'] | None = None
    applicationLimit: float | None = None
    applicationCycle: (
        Literal[
            'Contract2Weeks',
            'Contract4Weeks',
            'ContractYear',
            'CalendarMonth',
            'CalendarQuarter',
            'CalendarWeek',
            'ContractQuarter',
            'CalendarYear',
        ]
        | None
    ) = None
    applicationUnlimitedFlag: bool | None = None
    oneTimeFlag: bool | None = None
    coverAgreementTime: bool | None = None
    coverAgreementProduct: bool | None = None
    coverAgreementExpense: bool | None = None
    coverSalesTax: bool | None = None
    carryOverUnused: bool | None = None
    allowOverruns: bool | None = None
    expiredDays: int | None = None
    limit: int | None = None
    expireWhenZero: bool | None = None
    chargeToFirm: bool | None = None
    employeeCompRate: Literal['Actual', 'Hourly'] | None = None
    """
     Required On Updates;
    """
    employeeCompNotExceed: Literal['Billing', 'Amount', 'Percent'] | None = None
    compHourlyRate: float | None = None
    compLimitAmount: float | None = None
    billingCycle: BillingCycleReference | None = None
    billOneTimeFlag: bool | None = None
    billingTerms: BillingTermsReference | None = None
    invoicingCycle: Literal['ContractYear', 'CalendarYear'] | None = None
    """
     Required On Updates;
    """
    billToCompany: CompanyReference | None = None
    billToContact: ContactReference | None = None
    billToSite: SiteReference | None = None
    billAmount: float | None = None
    taxable: bool | None = None
    prorateFirstBill: float | None = None
    billStartDate: datetime | None = None
    taxCode: TaxCodeReference | None = None
    restrictDownPayment: bool | None = None
    prorateFlag: bool | None = None
    invoiceProratedAdditionsFlag: bool | None = None
    invoiceDescription: str | None = None
    topComment: bool | None = None
    bottomComment: bool | None = None
    workRole: WorkRoleReference | None = None
    workType: WorkTypeReference | None = None
    projectType: ProjectTypeReference | None = None
    invoiceTemplate: InvoiceTemplateReference | None = None
    billTime: Literal['Billable', 'DoNotBill', 'NoCharge', 'NoDefault'] | None = None
    """
     Required On Updates;
    """
    billExpenses: Literal['Billable', 'DoNotBill', 'NoCharge', 'NoDefault'] | None = (
        None
    )
    """
     Required On Updates;
    """
    billProducts: Literal['Billable', 'DoNotBill', 'NoCharge', 'NoDefault'] | None = (
        None
    )
    """
     Required On Updates;
    """
    billableTimeInvoice: bool | None = None
    billableExpenseInvoice: bool | None = None
    billableProductInvoice: bool | None = None
    currency: CurrencyReference | None = None
    periodType: Literal['Current', 'Future', 'Both', 'Undefined'] | None = None
    autoInvoiceFlag: bool | None = None
    nextInvoiceDate: str | None = None
    companyLocation: SystemLocationReference | None = None
    shipToCompany: CompanyReference | None = None
    shipToContact: ContactReference | None = None
    shipToSite: SiteReference | None = None
    agreementStatus: Literal['Active', 'Cancelled', 'Expired', 'Inactive'] | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')
    customFields: list[CustomFieldValue] | None = None


class Invoice(SparkModel):
    id: int | None = None
    invoiceNumber: str | None = None
    """
     Max length: 15; Required On Updates;
    """
    type: (
        Literal[
            'Agreement',
            'CreditMemo',
            'DownPayment',
            'Miscellaneous',
            'Progress',
            'Standard',
        ]
        | None
    ) = Field(...)
    status: BillingStatusReference | None = None
    company: CompanyReference
    billToCompany: CompanyReference | None = None
    shipToCompany: CompanyReference | None = None
    accountNumber: str | None = None
    applyToType: (
        Literal['All', 'Agreement', 'Project', 'ProjectPhase', 'SalesOrder', 'Ticket']
        | None
    ) = None
    applyToId: int | None = None
    attention: str | None = None
    """
     Max length: 60;
    """
    shipToAttention: str | None = None
    """
     Max length: 60;
    """
    billingSite: SiteReference | None = None
    billingSiteAddressLine1: str | None = None
    billingSiteAddressLine2: str | None = None
    billingSiteCity: str | None = None
    billingSiteState: str | None = None
    billingSiteZip: str | None = None
    billingSiteCountry: str | None = None
    shippingSite: SiteReference | None = None
    shippingSiteAddressLine1: str | None = None
    shippingSiteAddressLine2: str | None = None
    shippingSiteCity: str | None = None
    shippingSiteState: str | None = None
    shippingSiteZip: str | None = None
    shippingSiteCountry: str | None = None
    billingTerms: BillingTermsReference | None = None
    reference: str | None = None
    """
     Max length: 50;
    """
    customerPO: str | None = None
    """
     Max length: 50;
    """
    templateSetupId: int | None = None
    """
    Can be obtained via InvoiceTemplate report.
    """
    invoiceTemplate: InvoiceTemplateDetailReference | None = None
    emailTemplateId: int | None = None
    """
    Can be obtained via InvoiceEmailTemplate report.
    """
    addToBatchEmailList: bool | None = None
    date: datetime | None = None
    restrictDownpaymentFlag: bool | None = None
    locationId: int | None = None
    """
     Required On Updates;
    """
    location: SystemLocationReference | None = None
    departmentId: int | None = None
    """
    departmentId is only required for special invoices.
    """
    department: BillingUnitReference | None = None
    territoryId: int | None = None
    territory: SystemLocationReference | None = None
    topComment: str | None = None
    bottomComment: str | None = None
    taxableFlag: bool | None = None
    taxCode: TaxCodeReference | None = None
    internalNotes: str | None = None
    downpaymentPreviouslyTaxedFlag: bool | None = None
    serviceTotal: float | None = None
    overrideDownPaymentAmountFlag: bool | None = None
    currency: CurrencyReference | None = None
    dueDate: datetime | None = None
    expenseTotal: float | None = None
    productTotal: float | None = None
    previousProgressApplied: float | None = None
    serviceAdjustmentAmount: float | None = None
    agreementAmount: float | None = None
    downpaymentApplied: float | None = None
    subtotal: float | None = None
    total: float | None = None
    remainingDownpayment: float | None = None
    salesTax: float | None = None
    adjustmentReason: str | None = None
    adjustedBy: str | None = None
    closedBy: str | None = None
    payments: float | None = None
    credits: float | None = None
    balance: float | None = None
    specialInvoiceFlag: bool | None = None
    billingSetupReference: BillingSetupReference | None = None
    ticket: TicketReference | None = None
    project: ProjectReference | None = None
    phase: ProjectPhaseReference | None = None
    salesOrder: SalesOrderReference | None = None
    agreement: AgreementReference | None = None
    glBatch: BatchReference | None = None
    unbatchedBatch: BatchReference | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')
    customFields: list[CustomFieldValue] | None = None


# PostedInvoice is an alias of Invoice, used for consistency in some contexts
PostedInvoice = Invoice
