# generated by datamodel-codegen:
#   filename:  ExpenseEntry.json
#   timestamp: 2025-05-09T13:38:43+00:00

from __future__ import annotations

from pydantic import Field
from sparkdantic import SparkModel


class FieldInfo(SparkModel):
    expenseReport_href: str


class ExpenseReport(SparkModel):
    id: int
    name: str
    field_info: FieldInfo = Field(..., alias="_info")


class FieldInfo1(SparkModel):
    company_href: str
    mobileGuid: str


class Company(SparkModel):
    id: int
    identifier: str
    name: str
    field_info: FieldInfo1 = Field(..., alias="_info")


class FieldInfo2(SparkModel):
    type_href: str


class Type(SparkModel):
    id: int
    name: str
    field_info: FieldInfo2 = Field(..., alias="_info")


class FieldInfo3(SparkModel):
    member_href: str


class Member(SparkModel):
    id: int
    identifier: str
    name: str
    field_info: FieldInfo3 = Field(..., alias="_info")


class FieldInfo4(SparkModel):
    method_href: str


class PaymentMethod(SparkModel):
    id: int
    name: str
    field_info: FieldInfo4 = Field(..., alias="_info")


class FieldInfo5(SparkModel):
    classification_href: str


class Classification(SparkModel):
    id: int
    name: str
    field_info: FieldInfo5 = Field(..., alias="_info")


class FieldInfo6(SparkModel):
    currency_href: str


class Currency(SparkModel):
    id: int
    symbol: str
    currencyCode: str
    decimalSeparator: str
    numberOfDecimals: int
    thousandsSeparator: str
    negativeParenthesesFlag: bool
    displaySymbolFlag: bool
    currencyIdentifier: str
    displayIdFlag: bool
    rightAlign: bool
    name: str
    field_info: FieldInfo6 = Field(..., alias="_info")


class ExpenseEntry(SparkModel):
    id: int
    expenseReport: ExpenseReport
    company: Company
    chargeToId: int
    chargeToType: str
    type: Type
    member: Member
    paymentMethod: PaymentMethod
    classification: Classification
    amount: float
    billableOption: str
    date: str
    locationId: int
    businessUnitId: int
    invoiceAmount: float
    mobileGuid: str
    currency: Currency
    status: str
    billAmount: float
    agreementAmount: float
