# generated by datamodel-codegen:
#   filename:  UnpostedInvoice.json
#   timestamp: 2025-05-09T13:39:02+00:00

from __future__ import annotations

from pydantic import Field
from sparkdantic import SparkModel


class FieldInfo(SparkModel):
    location_href: str


class Location(SparkModel):
    id: int
    name: str
    field_info: FieldInfo = Field(..., alias="_info")


class FieldInfo1(SparkModel):
    company_href: str


class Company(SparkModel):
    id: int
    identifier: str
    name: str
    field_info: FieldInfo1 = Field(..., alias="_info")


class BillToCompany(SparkModel):
    id: int
    identifier: str
    name: str
    field_info: FieldInfo1 = Field(..., alias="_info")


class FieldInfo3(SparkModel):
    site_href: str


class BillToSite(SparkModel):
    id: int
    name: str
    field_info: FieldInfo3 = Field(..., alias="_info")


class FieldInfo4(SparkModel):
    company_href: str


class ShipToCompany(SparkModel):
    id: int
    identifier: str
    name: str
    field_info: FieldInfo4 = Field(..., alias="_info")


class FieldInfo5(SparkModel):
    site_href: str


class ShipToSite(SparkModel):
    id: int
    name: str
    field_info: FieldInfo5 = Field(..., alias="_info")


class BillingTerms(SparkModel):
    id: int
    name: str


class FieldInfo6(SparkModel):
    currency_href: str


class Currency(SparkModel):
    id: int
    currencyCode: str
    decimalSeparator: str
    numberOfDecimals: int
    thousandsSeparator: str
    negativeParenthesesFlag: bool
    displaySymbolFlag: bool
    currencyIdentifier: str
    displayIdFlag: bool
    rightAlign: bool
    name: str
    field_info: FieldInfo6 = Field(..., alias="_info")


class FieldInfo7(SparkModel):
    taxCode_href: str


class TaxCode(SparkModel):
    id: int
    name: str
    field_info: FieldInfo7 = Field(..., alias="_info")


class UnpostedInvoice(SparkModel):
    id: int
    billingLogId: int
    locationId: int
    location: Location
    company: Company
    accountNumber: str
    billToCompany: BillToCompany
    billToSite: BillToSite
    shipToCompany: ShipToCompany
    shipToSite: ShipToSite
    invoiceNumber: str
    invoiceDate: str
    invoiceType: str
    description: str
    billingTerms: BillingTerms
    dueDays: str
    dueDate: str
    currency: Currency
    subTotal: float
    total: float
    hasTime: bool
    hasExpenses: bool
    hasProducts: bool
    invoiceTaxableFlag: bool
    taxCode: TaxCode
    avalaraTaxFlag: bool
    itemTaxableFlag: bool
    salesTaxAmount: float
    stateTaxFlag: bool
    stateTaxAmount: float
    countyTaxFlag: bool
    countyTaxAmount: float
    cityTaxFlag: bool
    cityTaxAmount: float
    countryTaxFlag: bool
    countryTaxAmount: float
    compositeTaxFlag: bool
    compositeTaxAmount: float
    levelSixTaxFlag: bool
    levelSixTaxAmount: float
    createdBy: str
    dateClosed: str
