[project]
name = "unified-etl-core"
version = "1.0.0"
description = "Core ETL framework with medallion architecture"
authors = [{name = "Hákon Freyr Gunnarsson", email = "hakonf@wise.is"}]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.4",
    "sparkdantic",
    "requests>=2.28.0",
    "tenacity>=8.0.0",
    "pyyaml>=6.0.0",
    "tomli>=2.0.0",
    "click>=8.0.0",
    "datamodel-code-generator>=0.29.1",
    "structlog>=25.4.0",
]

[project.optional-dependencies]
local = [
    "pyspark>=3.3.0",
    "delta-spark>=2.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
