# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json
#   timestamp: 2025-05-27T16:44:24+00:00

from __future__ import annotations

from pydantic import Field
from sparkdantic import SparkModel


class CampaignSubType(SparkModel):
    id: int | None = None
    typeId: int | None = None
    name: str | None = None
    field_info: dict[str, str] | None = Field(None, alias='_info')
