# Agreement fact configuration for ConnectWise PSA
# Demonstrates proper grain for financial analytics

entities:
  agreement:
    source: connectwise
    endpoint: "/finance/agreements"
    bronze_table: "bronze_cw_agreements"
    silver_table: "silver_agreements"
    gold_tables:
      - "fact_agreement_period"     # Monthly grain for MRR tracking
      - "fact_agreement_summary"    # Lifetime summary per agreement
      - "dim_agreement"            # Agreement dimension
    
    # Gold layer transformations
    gold_transforms:
      fact_agreement_period:
        grain: "monthly"
        type: "period_snapshot"
        date_spine:
          start: "2020-01-01"
          frequency: "month"
        metrics:
          - monthly_revenue
          - prorated_revenue  
          - is_active_period
          - is_new_agreement
          - is_churned_agreement
          - months_since_start
          - revenue_change
          - cumulative_revenue
        keys:
          - name: "AgreementPeriodSK"
            source_columns: ["id", "period_start"]
            type: "hash"
          - name: "AgreementSK"
            source_columns: ["id"]
            type: "hash"
          - name: "DateSK"
            source_columns: ["period_start"]
            type: "date_int"
            
      fact_agreement_summary:
        grain: "agreement"
        type: "aggregate"
        metrics:
          - lifetime_days
          - lifetime_months
          - estimated_lifetime_value
          - actual_total_revenue      # From period facts
          - actual_avg_monthly_revenue # From period facts
          - active_periods            # Count of active months
        keys:
          - name: "AgreementSK"
            source_columns: ["id"]
            type: "hash"
            
      dim_agreement:
        type: "dimension"
        scd_type: 2  # Track changes over time
        natural_key: ["id"]
        attributes:
          - name
          - agreementStatus
          - type
          - company
          - contact
          - billCycleId
          - applicationUnits
          - cancelledFlag