# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema_patched.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel

from . import CustomFieldValue


class Adjustment(SparkModel):
    id: int | None = None
    amount: float | None = None
    description: Annotated[str | None, Field(description=' Max length: 1000;')] = None
    effectiveDate: datetime | None = None
    agreementId: int | None = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None
    customFields: list[CustomFieldValue] | None = None
