# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel

from . import CompanyReference, CompanyTypeReference


class CompanyTypeAssociation(SparkModel):
    id: int | None = None
    type: CompanyTypeReference | None = None
    company: CompanyReference | None = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None
