# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema_patched.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import Field
from sparkdantic import SparkModel

from . import (
    CompanyReference,
    CompanyTypeReference,
    ConfigurationQuestion,
    ConfigurationStatusReference,
    ConfigurationTypeReference,
    ContactReference,
    ContactTypeReference,
    CustomFieldValue,
    ManufacturerReference,
    MemberReference,
    SiteReference,
    SLAReference,
    SystemDepartmentReference,
    SystemLocationReference,
)


class CompanyTypeAssociation(SparkModel):
    id: int | None = None
    type: CompanyTypeReference | None = None
    company: CompanyReference | None = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None


class Configuration(SparkModel):
    id: int | None = None
    name: Annotated[str | None, Field(description=' Max length: 100;')] = None
    type: ConfigurationTypeReference | None = None
    status: ConfigurationStatusReference | None = None
    company: CompanyReference | None = None
    contact: ContactReference | None = None
    site: SiteReference | None = None
    locationId: int | None = None
    location: SystemLocationReference | None = None
    businessUnitId: int | None = None
    department: SystemDepartmentReference | None = None
    deviceIdentifier: Annotated[str | None, Field(description=' Max length: 100;')] = (
        None
    )
    serialNumber: Annotated[str | None, Field(description=' Max length: 250;')] = None
    modelNumber: Annotated[str | None, Field(description=' Max length: 50;')] = None
    tagNumber: Annotated[str | None, Field(description=' Max length: 50;')] = None
    purchaseDate: datetime | None = None
    installationDate: datetime | None = None
    installedBy: MemberReference | None = None
    warrantyExpirationDate: datetime | None = None
    vendorNotes: str | None = None
    notes: str | None = None
    macAddress: Annotated[str | None, Field(description=' Max length: 25;')] = None
    lastLoginName: Annotated[str | None, Field(description=' Max length: 100;')] = None
    billFlag: bool | None = None
    backupSuccesses: int | None = None
    backupIncomplete: int | None = None
    backupFailed: int | None = None
    backupRestores: int | None = None
    lastBackupDate: datetime | None = None
    backupServerName: Annotated[str | None, Field(description=' Max length: 50;')] = (
        None
    )
    backupBillableSpaceGb: float | None = None
    backupProtectedDeviceList: str | None = None
    backupYear: int | None = None
    backupMonth: int | None = None
    ipAddress: Annotated[str | None, Field(description=' Max length: 50;')] = None
    defaultGateway: Annotated[str | None, Field(description=' Max length: 50;')] = None
    osType: Annotated[str | None, Field(description=' Max length: 250;')] = None
    osInfo: Annotated[str | None, Field(description=' Max length: 250;')] = None
    cpuSpeed: Annotated[str | None, Field(description=' Max length: 100;')] = None
    ram: Annotated[str | None, Field(description=' Max length: 25;')] = None
    localHardDrives: str | None = None
    parentConfigurationId: int | None = None
    vendor: CompanyReference | None = None
    manufacturer: ManufacturerReference | None = None
    questions: list[ConfigurationQuestion] | None = None
    activeFlag: bool | None = None
    managementLink: Annotated[str | None, Field(description=' Max length: 1000;')] = (
        None
    )
    remoteLink: Annotated[str | None, Field(description=' Max length: 1000;')] = None
    sla: SLAReference | None = None
    mobileGuid: UUID | None = None
    displayVendorFlag: bool | None = None
    companyLocationId: int | None = None
    showRemoteFlag: bool | None = None
    showAutomateFlag: bool | None = None
    needsRenewalFlag: bool | None = None
    manufacturerPartNumber: Annotated[
        str | None, Field(description=' Max length: 50;')
    ] = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None
    customFields: list[CustomFieldValue] | None = None


class ContactTypeAssociation(SparkModel):
    id: int | None = None
    type: ContactTypeReference | None = None
    contact: ContactReference | None = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None
