# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel

from . import ContactReference, ContactTypeReference


class ContactTypeAssociation(SparkModel):
    id: int | None
    type: ContactTypeReference
    contact: ContactReference
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')]
