# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel

from . import CurrencyCodeReference


class Currency(SparkModel):
    id: int | None
    currencyIdentifier: Annotated[str, Field(description=' Max length: 10;')]
    name: Annotated[str, Field(description=' Max length: 50;')]
    symbol: Annotated[str | None, Field(description=' Max length: 10;')]
    displayIdFlag: bool | None
    displaySymbolFlag: bool | None
    currencyCode: CurrencyCodeReference | None
    thousandsSeparator: Annotated[str | None, Field(description=' Max length: 1;')]
    decimalSeparator: Annotated[str | None, Field(description=' Max length: 1;')]
    negativeParenthesesFlag: bool | None
    rightAlign: bool | None
    numberOfDecimals: int | None
    reportFormat: str | None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')]
