# generated by datamodel-codegen:
#   filename:  PSA_OpenAPI_schema_patched.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from sparkdantic import SparkModel

from . import CurrencyCodeReference


class Currency(SparkModel):
    id: int | None = None
    currencyIdentifier: Annotated[str | None, Field(description=' Max length: 10;')] = (
        None
    )
    name: Annotated[str | None, Field(description=' Max length: 50;')] = None
    symbol: Annotated[str | None, Field(description=' Max length: 10;')] = None
    displayIdFlag: bool | None = None
    displaySymbolFlag: bool | None = None
    currencyCode: CurrencyCodeReference | None = None
    thousandsSeparator: Annotated[str | None, Field(description=' Max length: 1;')] = (
        None
    )
    decimalSeparator: Annotated[str | None, Field(description=' Max length: 1;')] = None
    negativeParenthesesFlag: bool | None = None
    rightAlign: bool | None = None
    numberOfDecimals: int | None = None
    reportFormat: str | None = None
    field_info: Annotated[dict[str, str] | None, Field(alias='_info')] = None
