"""Models registry - separate from autogenerated code."""

from . import Agreement, Company, ExpenseEntry, Invoice, Member, ProductItem, TimeEntry

# Models dictionary for easy access
models = {
    "agreement": Agreement,
    "timeentry": TimeEntry,
    "invoice": Invoice,
    "expenseentry": ExpenseEntry,
    "productitem": ProductItem,
    "member": Member,
    "company": Company,
}