"""Models registry - separate from autogenerated code."""

from . import Agreement, Company, ExpenseEntry, ExpenseTax, Invoice, Member, ProductItem, TimeEntry

# Rebuild all models to resolve forward references
Agreement.model_rebuild()
TimeEntry.model_rebuild()
Invoice.model_rebuild()
ExpenseTax.model_rebuild()  # ExpenseEntry depends on this
ExpenseEntry.model_rebuild()
ProductItem.model_rebuild()
Member.model_rebuild()
Company.model_rebuild()

# Models dictionary for easy access
models = {
    "agreement": Agreement,
    "timeentry": TimeEntry,
    "invoice": Invoice,
    "expenseentry": ExpenseEntry,
    "productitem": ProductItem,
    "member": Member,
    "company": Company,
}